<?php
/**
 * BudgetUpload
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * 뱅크다K 웹앱 REST API
 *
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * BudgetUpload Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class BudgetUpload implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'BudgetUpload';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'esti_display' => 'string',
        'esti_inout' => 'string',
        'total_money' => 'string',
        'budget_item' => '\OpenAPI\Client\Model\BudgetUploadItem[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'esti_display' => null,
        'esti_inout' => null,
        'total_money' => null,
        'budget_item' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'esti_display' => 'ESTI_DISPLAY',
        'esti_inout' => 'ESTI_INOUT',
        'total_money' => 'TOTAL_MONEY',
        'budget_item' => 'budget_item'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'esti_display' => 'setEstiDisplay',
        'esti_inout' => 'setEstiInout',
        'total_money' => 'setTotalMoney',
        'budget_item' => 'setBudgetItem'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'esti_display' => 'getEstiDisplay',
        'esti_inout' => 'getEstiInout',
        'total_money' => 'getTotalMoney',
        'budget_item' => 'getBudgetItem'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['esti_display'] = $data['esti_display'] ?? null;
        $this->container['esti_inout'] = $data['esti_inout'] ?? null;
        $this->container['total_money'] = $data['total_money'] ?? null;
        $this->container['budget_item'] = $data['budget_item'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['esti_display'] === null) {
            $invalidProperties[] = "'esti_display' can't be null";
        }
        if ($this->container['esti_inout'] === null) {
            $invalidProperties[] = "'esti_inout' can't be null";
        }
        if ($this->container['total_money'] === null) {
            $invalidProperties[] = "'total_money' can't be null";
        }
        if ($this->container['budget_item'] === null) {
            $invalidProperties[] = "'budget_item' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets esti_display
     *
     * @return string
     */
    public function getEstiDisplay()
    {
        return $this->container['esti_display'];
    }

    /**
     * Sets esti_display
     *
     * @param string $esti_display 과목코드
     *
     * @return self
     */
    public function setEstiDisplay($esti_display)
    {
        $this->container['esti_display'] = $esti_display;

        return $this;
    }

    /**
     * Gets esti_inout
     *
     * @return string
     */
    public function getEstiInout()
    {
        return $this->container['esti_inout'];
    }

    /**
     * Sets esti_inout
     *
     * @param string $esti_inout 입출구분(I:세입, O:세출)
     *
     * @return self
     */
    public function setEstiInout($esti_inout)
    {
        $this->container['esti_inout'] = $esti_inout;

        return $this;
    }

    /**
     * Gets total_money
     *
     * @return string
     */
    public function getTotalMoney()
    {
        return $this->container['total_money'];
    }

    /**
     * Sets total_money
     *
     * @param string $total_money 예산합계
     *
     * @return self
     */
    public function setTotalMoney($total_money)
    {
        $this->container['total_money'] = $total_money;

        return $this;
    }

    /**
     * Gets budget_item
     *
     * @return \OpenAPI\Client\Model\BudgetUploadItem[]
     */
    public function getBudgetItem()
    {
        return $this->container['budget_item'];
    }

    /**
     * Sets budget_item
     *
     * @param \OpenAPI\Client\Model\BudgetUploadItem[] $budget_item 예산내역 목록
     *
     * @return self
     */
    public function setBudgetItem($budget_item)
    {
        $this->container['budget_item'] = $budget_item;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


