<?php
/**
 * SlipSplitDeleteUploadSlip
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * 뱅크다K 웹앱 REST API
 *
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * SlipSplitDeleteUploadSlip Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class SlipSplitDeleteUploadSlip implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SlipSplitDeleteUploadSlip';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'bill_date' => 'string',
        'bill_order_date' => 'string',
        'esti_code' => 'string',
        'esti_inout' => 'string',
        'bill_money' => 'string',
        'bill_memo' => 'string',
        'bill_bigo' => 'string',
        'bill_support_at' => 'string',
        'bill_nuri_at' => 'string',
        'setle_mthd' => 'string',
        'esti_idx' => 'string',
        'esti_name' => 'string',
        'esti_depth' => 'string',
        'esti_name_1' => 'string',
        'esti_name_2' => 'string',
        'esti_name_3' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'bill_date' => null,
        'bill_order_date' => null,
        'esti_code' => null,
        'esti_inout' => null,
        'bill_money' => null,
        'bill_memo' => null,
        'bill_bigo' => null,
        'bill_support_at' => null,
        'bill_nuri_at' => null,
        'setle_mthd' => null,
        'esti_idx' => null,
        'esti_name' => null,
        'esti_depth' => null,
        'esti_name_1' => null,
        'esti_name_2' => null,
        'esti_name_3' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'bill_date' => 'BILL_DATE',
        'bill_order_date' => 'BILL_ORDER_DATE',
        'esti_code' => 'ESTI_CODE',
        'esti_inout' => 'ESTI_INOUT',
        'bill_money' => 'BILL_MONEY',
        'bill_memo' => 'BILL_MEMO',
        'bill_bigo' => 'BILL_BIGO',
        'bill_support_at' => 'BILL_SUPPORT_AT',
        'bill_nuri_at' => 'BILL_NURI_AT',
        'setle_mthd' => 'SETLE_MTHD',
        'esti_idx' => 'ESTI_IDX',
        'esti_name' => 'ESTI_NAME',
        'esti_depth' => 'ESTI_DEPTH',
        'esti_name_1' => 'ESTI_NAME_1',
        'esti_name_2' => 'ESTI_NAME_2',
        'esti_name_3' => 'ESTI_NAME_3'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'bill_date' => 'setBillDate',
        'bill_order_date' => 'setBillOrderDate',
        'esti_code' => 'setEstiCode',
        'esti_inout' => 'setEstiInout',
        'bill_money' => 'setBillMoney',
        'bill_memo' => 'setBillMemo',
        'bill_bigo' => 'setBillBigo',
        'bill_support_at' => 'setBillSupportAt',
        'bill_nuri_at' => 'setBillNuriAt',
        'setle_mthd' => 'setSetleMthd',
        'esti_idx' => 'setEstiIdx',
        'esti_name' => 'setEstiName',
        'esti_depth' => 'setEstiDepth',
        'esti_name_1' => 'setEstiName1',
        'esti_name_2' => 'setEstiName2',
        'esti_name_3' => 'setEstiName3'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'bill_date' => 'getBillDate',
        'bill_order_date' => 'getBillOrderDate',
        'esti_code' => 'getEstiCode',
        'esti_inout' => 'getEstiInout',
        'bill_money' => 'getBillMoney',
        'bill_memo' => 'getBillMemo',
        'bill_bigo' => 'getBillBigo',
        'bill_support_at' => 'getBillSupportAt',
        'bill_nuri_at' => 'getBillNuriAt',
        'setle_mthd' => 'getSetleMthd',
        'esti_idx' => 'getEstiIdx',
        'esti_name' => 'getEstiName',
        'esti_depth' => 'getEstiDepth',
        'esti_name_1' => 'getEstiName1',
        'esti_name_2' => 'getEstiName2',
        'esti_name_3' => 'getEstiName3'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['bill_date'] = $data['bill_date'] ?? null;
        $this->container['bill_order_date'] = $data['bill_order_date'] ?? null;
        $this->container['esti_code'] = $data['esti_code'] ?? null;
        $this->container['esti_inout'] = $data['esti_inout'] ?? null;
        $this->container['bill_money'] = $data['bill_money'] ?? null;
        $this->container['bill_memo'] = $data['bill_memo'] ?? null;
        $this->container['bill_bigo'] = $data['bill_bigo'] ?? null;
        $this->container['bill_support_at'] = $data['bill_support_at'] ?? null;
        $this->container['bill_nuri_at'] = $data['bill_nuri_at'] ?? null;
        $this->container['setle_mthd'] = $data['setle_mthd'] ?? null;
        $this->container['esti_idx'] = $data['esti_idx'] ?? null;
        $this->container['esti_name'] = $data['esti_name'] ?? null;
        $this->container['esti_depth'] = $data['esti_depth'] ?? null;
        $this->container['esti_name_1'] = $data['esti_name_1'] ?? null;
        $this->container['esti_name_2'] = $data['esti_name_2'] ?? null;
        $this->container['esti_name_3'] = $data['esti_name_3'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['bill_date'] === null) {
            $invalidProperties[] = "'bill_date' can't be null";
        }
        if ($this->container['bill_order_date'] === null) {
            $invalidProperties[] = "'bill_order_date' can't be null";
        }
        if ($this->container['esti_code'] === null) {
            $invalidProperties[] = "'esti_code' can't be null";
        }
        if ($this->container['esti_inout'] === null) {
            $invalidProperties[] = "'esti_inout' can't be null";
        }
        if ($this->container['bill_money'] === null) {
            $invalidProperties[] = "'bill_money' can't be null";
        }
        if ($this->container['bill_memo'] === null) {
            $invalidProperties[] = "'bill_memo' can't be null";
        }
        if ($this->container['bill_bigo'] === null) {
            $invalidProperties[] = "'bill_bigo' can't be null";
        }
        if ($this->container['bill_support_at'] === null) {
            $invalidProperties[] = "'bill_support_at' can't be null";
        }
        if ($this->container['bill_nuri_at'] === null) {
            $invalidProperties[] = "'bill_nuri_at' can't be null";
        }
        if ($this->container['setle_mthd'] === null) {
            $invalidProperties[] = "'setle_mthd' can't be null";
        }
        if ($this->container['esti_idx'] === null) {
            $invalidProperties[] = "'esti_idx' can't be null";
        }
        if ($this->container['esti_name'] === null) {
            $invalidProperties[] = "'esti_name' can't be null";
        }
        if ($this->container['esti_depth'] === null) {
            $invalidProperties[] = "'esti_depth' can't be null";
        }
        if ($this->container['esti_name_1'] === null) {
            $invalidProperties[] = "'esti_name_1' can't be null";
        }
        if ($this->container['esti_name_2'] === null) {
            $invalidProperties[] = "'esti_name_2' can't be null";
        }
        if ($this->container['esti_name_3'] === null) {
            $invalidProperties[] = "'esti_name_3' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets bill_date
     *
     * @return string
     */
    public function getBillDate()
    {
        return $this->container['bill_date'];
    }

    /**
     * Sets bill_date
     *
     * @param string $bill_date 일자(YYYYMMDD)
     *
     * @return self
     */
    public function setBillDate($bill_date)
    {
        $this->container['bill_date'] = $bill_date;

        return $this;
    }

    /**
     * Gets bill_order_date
     *
     * @return string
     */
    public function getBillOrderDate()
    {
        return $this->container['bill_order_date'];
    }

    /**
     * Sets bill_order_date
     *
     * @param string $bill_order_date bill_order_date
     *
     * @return self
     */
    public function setBillOrderDate($bill_order_date)
    {
        $this->container['bill_order_date'] = $bill_order_date;

        return $this;
    }

    /**
     * Gets esti_code
     *
     * @return string
     */
    public function getEstiCode()
    {
        return $this->container['esti_code'];
    }

    /**
     * Sets esti_code
     *
     * @param string $esti_code 과목코드
     *
     * @return self
     */
    public function setEstiCode($esti_code)
    {
        $this->container['esti_code'] = $esti_code;

        return $this;
    }

    /**
     * Gets esti_inout
     *
     * @return string
     */
    public function getEstiInout()
    {
        return $this->container['esti_inout'];
    }

    /**
     * Sets esti_inout
     *
     * @param string $esti_inout 입출구분(I:세입, O:세출)
     *
     * @return self
     */
    public function setEstiInout($esti_inout)
    {
        $this->container['esti_inout'] = $esti_inout;

        return $this;
    }

    /**
     * Gets bill_money
     *
     * @return string
     */
    public function getBillMoney()
    {
        return $this->container['bill_money'];
    }

    /**
     * Sets bill_money
     *
     * @param string $bill_money bill_money
     *
     * @return self
     */
    public function setBillMoney($bill_money)
    {
        $this->container['bill_money'] = $bill_money;

        return $this;
    }

    /**
     * Gets bill_memo
     *
     * @return string
     */
    public function getBillMemo()
    {
        return $this->container['bill_memo'];
    }

    /**
     * Sets bill_memo
     *
     * @param string $bill_memo 전표메모(공란)
     *
     * @return self
     */
    public function setBillMemo($bill_memo)
    {
        $this->container['bill_memo'] = $bill_memo;

        return $this;
    }

    /**
     * Gets bill_bigo
     *
     * @return string
     */
    public function getBillBigo()
    {
        return $this->container['bill_bigo'];
    }

    /**
     * Sets bill_bigo
     *
     * @param string $bill_bigo 비고내용
     *
     * @return self
     */
    public function setBillBigo($bill_bigo)
    {
        $this->container['bill_bigo'] = $bill_bigo;

        return $this;
    }

    /**
     * Gets bill_support_at
     *
     * @return string
     */
    public function getBillSupportAt()
    {
        return $this->container['bill_support_at'];
    }

    /**
     * Sets bill_support_at
     *
     * @param string $bill_support_at bill_support_at
     *
     * @return self
     */
    public function setBillSupportAt($bill_support_at)
    {
        $this->container['bill_support_at'] = $bill_support_at;

        return $this;
    }

    /**
     * Gets bill_nuri_at
     *
     * @return string
     */
    public function getBillNuriAt()
    {
        return $this->container['bill_nuri_at'];
    }

    /**
     * Sets bill_nuri_at
     *
     * @param string $bill_nuri_at bill_nuri_at
     *
     * @return self
     */
    public function setBillNuriAt($bill_nuri_at)
    {
        $this->container['bill_nuri_at'] = $bill_nuri_at;

        return $this;
    }

    /**
     * Gets setle_mthd
     *
     * @return string
     */
    public function getSetleMthd()
    {
        return $this->container['setle_mthd'];
    }

    /**
     * Sets setle_mthd
     *
     * @param string $setle_mthd setle_mthd
     *
     * @return self
     */
    public function setSetleMthd($setle_mthd)
    {
        $this->container['setle_mthd'] = $setle_mthd;

        return $this;
    }

    /**
     * Gets esti_idx
     *
     * @return string
     */
    public function getEstiIdx()
    {
        return $this->container['esti_idx'];
    }

    /**
     * Sets esti_idx
     *
     * @param string $esti_idx esti_idx
     *
     * @return self
     */
    public function setEstiIdx($esti_idx)
    {
        $this->container['esti_idx'] = $esti_idx;

        return $this;
    }

    /**
     * Gets esti_name
     *
     * @return string
     */
    public function getEstiName()
    {
        return $this->container['esti_name'];
    }

    /**
     * Sets esti_name
     *
     * @param string $esti_name esti_name
     *
     * @return self
     */
    public function setEstiName($esti_name)
    {
        $this->container['esti_name'] = $esti_name;

        return $this;
    }

    /**
     * Gets esti_depth
     *
     * @return string
     */
    public function getEstiDepth()
    {
        return $this->container['esti_depth'];
    }

    /**
     * Sets esti_depth
     *
     * @param string $esti_depth esti_depth
     *
     * @return self
     */
    public function setEstiDepth($esti_depth)
    {
        $this->container['esti_depth'] = $esti_depth;

        return $this;
    }

    /**
     * Gets esti_name_1
     *
     * @return string
     */
    public function getEstiName1()
    {
        return $this->container['esti_name_1'];
    }

    /**
     * Sets esti_name_1
     *
     * @param string $esti_name_1 esti_name_1
     *
     * @return self
     */
    public function setEstiName1($esti_name_1)
    {
        $this->container['esti_name_1'] = $esti_name_1;

        return $this;
    }

    /**
     * Gets esti_name_2
     *
     * @return string
     */
    public function getEstiName2()
    {
        return $this->container['esti_name_2'];
    }

    /**
     * Sets esti_name_2
     *
     * @param string $esti_name_2 esti_name_2
     *
     * @return self
     */
    public function setEstiName2($esti_name_2)
    {
        $this->container['esti_name_2'] = $esti_name_2;

        return $this;
    }

    /**
     * Gets esti_name_3
     *
     * @return string
     */
    public function getEstiName3()
    {
        return $this->container['esti_name_3'];
    }

    /**
     * Sets esti_name_3
     *
     * @param string $esti_name_3 esti_name_3
     *
     * @return self
     */
    public function setEstiName3($esti_name_3)
    {
        $this->container['esti_name_3'] = $esti_name_3;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


