/*
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.BudgetUploadItem;

/**
 * BudgetUpload
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-06-18T15:11:40.792001100+09:00[Asia/Seoul]")
public class BudgetUpload {
  public static final String SERIALIZED_NAME_E_S_T_I_D_I_S_P_L_A_Y = "ESTI_DISPLAY";
  @SerializedName(SERIALIZED_NAME_E_S_T_I_D_I_S_P_L_A_Y)
  private String ESTI_DISPLAY;

  public static final String SERIALIZED_NAME_E_S_T_I_I_N_O_U_T = "ESTI_INOUT";
  @SerializedName(SERIALIZED_NAME_E_S_T_I_I_N_O_U_T)
  private String ESTI_INOUT;

  public static final String SERIALIZED_NAME_T_O_T_A_L_M_O_N_E_Y = "TOTAL_MONEY";
  @SerializedName(SERIALIZED_NAME_T_O_T_A_L_M_O_N_E_Y)
  private String TOTAL_MONEY;

  public static final String SERIALIZED_NAME_BUDGET_ITEM = "budget_item";
  @SerializedName(SERIALIZED_NAME_BUDGET_ITEM)
  private List<BudgetUploadItem> budgetItem = new ArrayList<BudgetUploadItem>();


  public BudgetUpload ESTI_DISPLAY(String ESTI_DISPLAY) {
    
    this.ESTI_DISPLAY = ESTI_DISPLAY;
    return this;
  }

   /**
   * 과목코드
   * @return ESTI_DISPLAY
  **/
  @ApiModelProperty(required = true, value = "과목코드")

  public String getESTIDISPLAY() {
    return ESTI_DISPLAY;
  }


  public void setESTIDISPLAY(String ESTI_DISPLAY) {
    this.ESTI_DISPLAY = ESTI_DISPLAY;
  }


  public BudgetUpload ESTI_INOUT(String ESTI_INOUT) {
    
    this.ESTI_INOUT = ESTI_INOUT;
    return this;
  }

   /**
   * 입출구분(I:세입, O:세출)
   * @return ESTI_INOUT
  **/
  @ApiModelProperty(required = true, value = "입출구분(I:세입, O:세출)")

  public String getESTIINOUT() {
    return ESTI_INOUT;
  }


  public void setESTIINOUT(String ESTI_INOUT) {
    this.ESTI_INOUT = ESTI_INOUT;
  }


  public BudgetUpload TOTAL_MONEY(String TOTAL_MONEY) {
    
    this.TOTAL_MONEY = TOTAL_MONEY;
    return this;
  }

   /**
   * 예산합계
   * @return TOTAL_MONEY
  **/
  @ApiModelProperty(required = true, value = "예산합계")

  public String getTOTALMONEY() {
    return TOTAL_MONEY;
  }


  public void setTOTALMONEY(String TOTAL_MONEY) {
    this.TOTAL_MONEY = TOTAL_MONEY;
  }


  public BudgetUpload budgetItem(List<BudgetUploadItem> budgetItem) {
    
    this.budgetItem = budgetItem;
    return this;
  }

  public BudgetUpload addBudgetItemItem(BudgetUploadItem budgetItemItem) {
    this.budgetItem.add(budgetItemItem);
    return this;
  }

   /**
   * 예산내역 목록
   * @return budgetItem
  **/
  @ApiModelProperty(required = true, value = "예산내역 목록")

  public List<BudgetUploadItem> getBudgetItem() {
    return budgetItem;
  }


  public void setBudgetItem(List<BudgetUploadItem> budgetItem) {
    this.budgetItem = budgetItem;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BudgetUpload budgetUpload = (BudgetUpload) o;
    return Objects.equals(this.ESTI_DISPLAY, budgetUpload.ESTI_DISPLAY) &&
        Objects.equals(this.ESTI_INOUT, budgetUpload.ESTI_INOUT) &&
        Objects.equals(this.TOTAL_MONEY, budgetUpload.TOTAL_MONEY) &&
        Objects.equals(this.budgetItem, budgetUpload.budgetItem);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ESTI_DISPLAY, ESTI_INOUT, TOTAL_MONEY, budgetItem);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BudgetUpload {\n");
    sb.append("    ESTI_DISPLAY: ").append(toIndentedString(ESTI_DISPLAY)).append("\n");
    sb.append("    ESTI_INOUT: ").append(toIndentedString(ESTI_INOUT)).append("\n");
    sb.append("    TOTAL_MONEY: ").append(toIndentedString(TOTAL_MONEY)).append("\n");
    sb.append("    budgetItem: ").append(toIndentedString(budgetItem)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

