/*
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.UserService;

/**
 * Connect
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-06-18T15:11:40.792001100+09:00[Asia/Seoul]")
public class Connect {
  public static final String SERIALIZED_NAME_USER_SERVICE = "userService";
  @SerializedName(SERIALIZED_NAME_USER_SERVICE)
  private UserService userService;


  public Connect userService(UserService userService) {
    
    this.userService = userService;
    return this;
  }

   /**
   * 유저별 사용하는 서비스
   * @return userService
  **/
  @ApiModelProperty(required = true, value = "유저별 사용하는 서비스")

  public UserService getUserService() {
    return userService;
  }


  public void setUserService(UserService userService) {
    this.userService = userService;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Connect connect = (Connect) o;
    return Objects.equals(this.userService, connect.userService);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userService);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Connect {\n");
    sb.append("    userService: ").append(toIndentedString(userService)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

