/*
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ChargeJangbuPartnership;
import org.threeten.bp.OffsetDateTime;

/**
 * Jangbu
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-06-18T15:11:40.792001100+09:00[Asia/Seoul]")
public class Jangbu {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private BigDecimal id;

  public static final String SERIALIZED_NAME_REP_ID = "repId";
  @SerializedName(SERIALIZED_NAME_REP_ID)
  private String repId;

  public static final String SERIALIZED_NAME_ACTIVE = "active";
  @SerializedName(SERIALIZED_NAME_ACTIVE)
  private Boolean active;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_TAX_EMAIL = "taxEmail";
  @SerializedName(SERIALIZED_NAME_TAX_EMAIL)
  private String taxEmail;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_CHARGE_JANGBU_PARTNERSHIPS = "chargeJangbuPartnerships";
  @SerializedName(SERIALIZED_NAME_CHARGE_JANGBU_PARTNERSHIPS)
  private List<ChargeJangbuPartnership> chargeJangbuPartnerships = null;


  public Jangbu id(BigDecimal id) {
    
    this.id = id;
    return this;
  }

   /**
   * 장부사번호
   * @return id
  **/
  @ApiModelProperty(required = true, value = "장부사번호")

  public BigDecimal getId() {
    return id;
  }


  public void setId(BigDecimal id) {
    this.id = id;
  }


  public Jangbu repId(String repId) {
    
    this.repId = repId;
    return this;
  }

   /**
   * 장부사 아이디
   * @return repId
  **/
  @ApiModelProperty(required = true, value = "장부사 아이디")

  public String getRepId() {
    return repId;
  }


  public void setRepId(String repId) {
    this.repId = repId;
  }


  public Jangbu active(Boolean active) {
    
    this.active = active;
    return this;
  }

   /**
   * 유효성여부
   * @return active
  **/
  @ApiModelProperty(required = true, value = "유효성여부")

  public Boolean getActive() {
    return active;
  }


  public void setActive(Boolean active) {
    this.active = active;
  }


  public Jangbu name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * 장부사명
   * @return name
  **/
  @ApiModelProperty(required = true, value = "장부사명")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public Jangbu taxEmail(String taxEmail) {
    
    this.taxEmail = taxEmail;
    return this;
  }

   /**
   * 과금 이메일
   * @return taxEmail
  **/
  @ApiModelProperty(required = true, value = "과금 이메일")

  public String getTaxEmail() {
    return taxEmail;
  }


  public void setTaxEmail(String taxEmail) {
    this.taxEmail = taxEmail;
  }


  public Jangbu createdAt(OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * 생성일자
   * @return createdAt
  **/
  @ApiModelProperty(required = true, value = "생성일자")

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public Jangbu chargeJangbuPartnerships(List<ChargeJangbuPartnership> chargeJangbuPartnerships) {
    
    this.chargeJangbuPartnerships = chargeJangbuPartnerships;
    return this;
  }

  public Jangbu addChargeJangbuPartnershipsItem(ChargeJangbuPartnership chargeJangbuPartnershipsItem) {
    if (this.chargeJangbuPartnerships == null) {
      this.chargeJangbuPartnerships = new ArrayList<ChargeJangbuPartnership>();
    }
    this.chargeJangbuPartnerships.add(chargeJangbuPartnershipsItem);
    return this;
  }

   /**
   * 계좌통합서비스 정보목록
   * @return chargeJangbuPartnerships
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "계좌통합서비스 정보목록")

  public List<ChargeJangbuPartnership> getChargeJangbuPartnerships() {
    return chargeJangbuPartnerships;
  }


  public void setChargeJangbuPartnerships(List<ChargeJangbuPartnership> chargeJangbuPartnerships) {
    this.chargeJangbuPartnerships = chargeJangbuPartnerships;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Jangbu jangbu = (Jangbu) o;
    return Objects.equals(this.id, jangbu.id) &&
        Objects.equals(this.repId, jangbu.repId) &&
        Objects.equals(this.active, jangbu.active) &&
        Objects.equals(this.name, jangbu.name) &&
        Objects.equals(this.taxEmail, jangbu.taxEmail) &&
        Objects.equals(this.createdAt, jangbu.createdAt) &&
        Objects.equals(this.chargeJangbuPartnerships, jangbu.chargeJangbuPartnerships);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, repId, active, name, taxEmail, createdAt, chargeJangbuPartnerships);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Jangbu {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    repId: ").append(toIndentedString(repId)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    taxEmail: ").append(toIndentedString(taxEmail)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    chargeJangbuPartnerships: ").append(toIndentedString(chargeJangbuPartnerships)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

