/*
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PcClient
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-06-18T15:11:40.792001100+09:00[Asia/Seoul]")
public class PcClient {
  public static final String SERIALIZED_NAME_PC_ID = "pcId";
  @SerializedName(SERIALIZED_NAME_PC_ID)
  private String pcId;

  public static final String SERIALIZED_NAME_CLIENT_INFO = "clientInfo";
  @SerializedName(SERIALIZED_NAME_CLIENT_INFO)
  private String clientInfo;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private String createdAt;


  public PcClient pcId(String pcId) {
    
    this.pcId = pcId;
    return this;
  }

   /**
   * 클라이언트 PC의 UUID 정보
   * @return pcId
  **/
  @ApiModelProperty(required = true, value = "클라이언트 PC의 UUID 정보")

  public String getPcId() {
    return pcId;
  }


  public void setPcId(String pcId) {
    this.pcId = pcId;
  }


  public PcClient clientInfo(String clientInfo) {
    
    this.clientInfo = clientInfo;
    return this;
  }

   /**
   * 클라이언트 시스템 정보(json)
   * @return clientInfo
  **/
  @ApiModelProperty(required = true, value = "클라이언트 시스템 정보(json)")

  public String getClientInfo() {
    return clientInfo;
  }


  public void setClientInfo(String clientInfo) {
    this.clientInfo = clientInfo;
  }


  public PcClient createdAt(String createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * 생성일자
   * @return createdAt
  **/
  @ApiModelProperty(required = true, value = "생성일자")

  public String getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PcClient pcClient = (PcClient) o;
    return Objects.equals(this.pcId, pcClient.pcId) &&
        Objects.equals(this.clientInfo, pcClient.clientInfo) &&
        Objects.equals(this.createdAt, pcClient.createdAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pcId, clientInfo, createdAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PcClient {\n");
    sb.append("    pcId: ").append(toIndentedString(pcId)).append("\n");
    sb.append("    clientInfo: ").append(toIndentedString(clientInfo)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

