/*
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets ProcessFlag
 */
@JsonAdapter(ProcessFlag.Adapter.class)
public enum ProcessFlag {
  
  _("접수"),
  
  _("승인"),
  
  _("진행"),
  
  _("실패"),
  
  _("접수실패"),
  
  _("성공"),
  
  _("자동취소"),
  
  _("수동취소"),
  
  _("중복취소");

  private String value;

  ProcessFlag(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ProcessFlag fromValue(String value) {
    for (ProcessFlag b : ProcessFlag.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<ProcessFlag> {
    @Override
    public void write(final JsonWriter jsonWriter, final ProcessFlag enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ProcessFlag read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ProcessFlag.fromValue(value);
    }
  }
}

