/*
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.threeten.bp.OffsetDateTime;

/**
 * Recovery
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-06-18T15:11:40.792001100+09:00[Asia/Seoul]")
public class Recovery {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_USER_SEQ = "userSeq";
  @SerializedName(SERIALIZED_NAME_USER_SEQ)
  private BigDecimal userSeq;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private OffsetDateTime updatedAt;

  public static final String SERIALIZED_NAME_EXPIRED_AT = "expiredAt";
  @SerializedName(SERIALIZED_NAME_EXPIRED_AT)
  private OffsetDateTime expiredAt;

  public static final String SERIALIZED_NAME_USED_AT = "usedAt";
  @SerializedName(SERIALIZED_NAME_USED_AT)
  private OffsetDateTime usedAt;


  public Recovery id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * 비밀번호 초기화키
   * @return id
  **/
  @ApiModelProperty(required = true, value = "비밀번호 초기화키")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public Recovery userSeq(BigDecimal userSeq) {
    
    this.userSeq = userSeq;
    return this;
  }

   /**
   * 회원 번호
   * @return userSeq
  **/
  @ApiModelProperty(required = true, value = "회원 번호")

  public BigDecimal getUserSeq() {
    return userSeq;
  }


  public void setUserSeq(BigDecimal userSeq) {
    this.userSeq = userSeq;
  }


  public Recovery createdAt(OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * 생성일
   * @return createdAt
  **/
  @ApiModelProperty(required = true, value = "생성일")

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public Recovery updatedAt(OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * 수정일
   * @return updatedAt
  **/
  @ApiModelProperty(required = true, value = "수정일")

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public Recovery expiredAt(OffsetDateTime expiredAt) {
    
    this.expiredAt = expiredAt;
    return this;
  }

   /**
   * 만료일
   * @return expiredAt
  **/
  @ApiModelProperty(required = true, value = "만료일")

  public OffsetDateTime getExpiredAt() {
    return expiredAt;
  }


  public void setExpiredAt(OffsetDateTime expiredAt) {
    this.expiredAt = expiredAt;
  }


  public Recovery usedAt(OffsetDateTime usedAt) {
    
    this.usedAt = usedAt;
    return this;
  }

   /**
   * 사용일
   * @return usedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "사용일")

  public OffsetDateTime getUsedAt() {
    return usedAt;
  }


  public void setUsedAt(OffsetDateTime usedAt) {
    this.usedAt = usedAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Recovery recovery = (Recovery) o;
    return Objects.equals(this.id, recovery.id) &&
        Objects.equals(this.userSeq, recovery.userSeq) &&
        Objects.equals(this.createdAt, recovery.createdAt) &&
        Objects.equals(this.updatedAt, recovery.updatedAt) &&
        Objects.equals(this.expiredAt, recovery.expiredAt) &&
        Objects.equals(this.usedAt, recovery.usedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, userSeq, createdAt, updatedAt, expiredAt, usedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Recovery {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    userSeq: ").append(toIndentedString(userSeq)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    expiredAt: ").append(toIndentedString(expiredAt)).append("\n");
    sb.append("    usedAt: ").append(toIndentedString(usedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

