/*
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.AdjustJangbuService;
import org.openapitools.client.model.ChargeJangbu;
import org.openapitools.client.model.ChargeJangbuPartnership;

/**
 * RegisterAdjustOutput
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-06-18T15:11:40.792001100+09:00[Asia/Seoul]")
public class RegisterAdjustOutput {
  public static final String SERIALIZED_NAME_STEP = "step";
  @SerializedName(SERIALIZED_NAME_STEP)
  private BigDecimal step;

  public static final String SERIALIZED_NAME_ADJUST_JANGBU_SERVICES = "adjustJangbuServices";
  @SerializedName(SERIALIZED_NAME_ADJUST_JANGBU_SERVICES)
  private List<AdjustJangbuService> adjustJangbuServices = null;

  public static final String SERIALIZED_NAME_CHARGE_JANGBU_PARTNERSHIP = "chargeJangbuPartnership";
  @SerializedName(SERIALIZED_NAME_CHARGE_JANGBU_PARTNERSHIP)
  private ChargeJangbuPartnership chargeJangbuPartnership;

  public static final String SERIALIZED_NAME_CHARGE_JANGBU = "chargeJangbu";
  @SerializedName(SERIALIZED_NAME_CHARGE_JANGBU)
  private ChargeJangbu chargeJangbu;


  public RegisterAdjustOutput step(BigDecimal step) {
    
    this.step = step;
    return this;
  }

   /**
   * 진행된 정산내역 등록단계
   * @return step
  **/
  @ApiModelProperty(required = true, value = "진행된 정산내역 등록단계")

  public BigDecimal getStep() {
    return step;
  }


  public void setStep(BigDecimal step) {
    this.step = step;
  }


  public RegisterAdjustOutput adjustJangbuServices(List<AdjustJangbuService> adjustJangbuServices) {
    
    this.adjustJangbuServices = adjustJangbuServices;
    return this;
  }

  public RegisterAdjustOutput addAdjustJangbuServicesItem(AdjustJangbuService adjustJangbuServicesItem) {
    if (this.adjustJangbuServices == null) {
      this.adjustJangbuServices = new ArrayList<AdjustJangbuService>();
    }
    this.adjustJangbuServices.add(adjustJangbuServicesItem);
    return this;
  }

   /**
   * (1단계진행시 반환정보) 장부사 서비스별 단가목록
   * @return adjustJangbuServices
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "(1단계진행시 반환정보) 장부사 서비스별 단가목록")

  public List<AdjustJangbuService> getAdjustJangbuServices() {
    return adjustJangbuServices;
  }


  public void setAdjustJangbuServices(List<AdjustJangbuService> adjustJangbuServices) {
    this.adjustJangbuServices = adjustJangbuServices;
  }


  public RegisterAdjustOutput chargeJangbuPartnership(ChargeJangbuPartnership chargeJangbuPartnership) {
    
    this.chargeJangbuPartnership = chargeJangbuPartnership;
    return this;
  }

   /**
   * (1단계진행시 반환정보) 장부사 계좌통합서비스 정보
   * @return chargeJangbuPartnership
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "(1단계진행시 반환정보) 장부사 계좌통합서비스 정보")

  public ChargeJangbuPartnership getChargeJangbuPartnership() {
    return chargeJangbuPartnership;
  }


  public void setChargeJangbuPartnership(ChargeJangbuPartnership chargeJangbuPartnership) {
    this.chargeJangbuPartnership = chargeJangbuPartnership;
  }


  public RegisterAdjustOutput chargeJangbu(ChargeJangbu chargeJangbu) {
    
    this.chargeJangbu = chargeJangbu;
    return this;
  }

   /**
   * (2단계진행시 반환정보) 해당연월 장부사 정산금액
   * @return chargeJangbu
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "(2단계진행시 반환정보) 해당연월 장부사 정산금액")

  public ChargeJangbu getChargeJangbu() {
    return chargeJangbu;
  }


  public void setChargeJangbu(ChargeJangbu chargeJangbu) {
    this.chargeJangbu = chargeJangbu;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegisterAdjustOutput registerAdjustOutput = (RegisterAdjustOutput) o;
    return Objects.equals(this.step, registerAdjustOutput.step) &&
        Objects.equals(this.adjustJangbuServices, registerAdjustOutput.adjustJangbuServices) &&
        Objects.equals(this.chargeJangbuPartnership, registerAdjustOutput.chargeJangbuPartnership) &&
        Objects.equals(this.chargeJangbu, registerAdjustOutput.chargeJangbu);
  }

  @Override
  public int hashCode() {
    return Objects.hash(step, adjustJangbuServices, chargeJangbuPartnership, chargeJangbu);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegisterAdjustOutput {\n");
    sb.append("    step: ").append(toIndentedString(step)).append("\n");
    sb.append("    adjustJangbuServices: ").append(toIndentedString(adjustJangbuServices)).append("\n");
    sb.append("    chargeJangbuPartnership: ").append(toIndentedString(chargeJangbuPartnership)).append("\n");
    sb.append("    chargeJangbu: ").append(toIndentedString(chargeJangbu)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

