/*
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.RoleListItem;

/**
 * RoleGroup
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-06-18T15:11:40.792001100+09:00[Asia/Seoul]")
public class RoleGroup {
  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  private String code;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_DESC = "desc";
  @SerializedName(SERIALIZED_NAME_DESC)
  private String desc;

  public static final String SERIALIZED_NAME_USER_LEVEL = "userLevel";
  @SerializedName(SERIALIZED_NAME_USER_LEVEL)
  private BigDecimal userLevel;

  public static final String SERIALIZED_NAME_ACTIVE = "active";
  @SerializedName(SERIALIZED_NAME_ACTIVE)
  private Boolean active;

  public static final String SERIALIZED_NAME_ROLE_LIST = "roleList";
  @SerializedName(SERIALIZED_NAME_ROLE_LIST)
  private List<RoleListItem> roleList = new ArrayList<RoleListItem>();


  public RoleGroup code(String code) {
    
    this.code = code;
    return this;
  }

   /**
   * 권한그룹 코드
   * @return code
  **/
  @ApiModelProperty(required = true, value = "권한그룹 코드")

  public String getCode() {
    return code;
  }


  public void setCode(String code) {
    this.code = code;
  }


  public RoleGroup name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * 권한그룹명
   * @return name
  **/
  @ApiModelProperty(required = true, value = "권한그룹명")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public RoleGroup desc(String desc) {
    
    this.desc = desc;
    return this;
  }

   /**
   * 권한그룹 설명
   * @return desc
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "권한그룹 설명")

  public String getDesc() {
    return desc;
  }


  public void setDesc(String desc) {
    this.desc = desc;
  }


  public RoleGroup userLevel(BigDecimal userLevel) {
    
    this.userLevel = userLevel;
    return this;
  }

   /**
   * 회원 레벨
   * @return userLevel
  **/
  @ApiModelProperty(required = true, value = "회원 레벨")

  public BigDecimal getUserLevel() {
    return userLevel;
  }


  public void setUserLevel(BigDecimal userLevel) {
    this.userLevel = userLevel;
  }


  public RoleGroup active(Boolean active) {
    
    this.active = active;
    return this;
  }

   /**
   * 활성여부
   * @return active
  **/
  @ApiModelProperty(required = true, value = "활성여부")

  public Boolean getActive() {
    return active;
  }


  public void setActive(Boolean active) {
    this.active = active;
  }


  public RoleGroup roleList(List<RoleListItem> roleList) {
    
    this.roleList = roleList;
    return this;
  }

  public RoleGroup addRoleListItem(RoleListItem roleListItem) {
    this.roleList.add(roleListItem);
    return this;
  }

   /**
   * 권한 목록
   * @return roleList
  **/
  @ApiModelProperty(required = true, value = "권한 목록")

  public List<RoleListItem> getRoleList() {
    return roleList;
  }


  public void setRoleList(List<RoleListItem> roleList) {
    this.roleList = roleList;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RoleGroup roleGroup = (RoleGroup) o;
    return Objects.equals(this.code, roleGroup.code) &&
        Objects.equals(this.name, roleGroup.name) &&
        Objects.equals(this.desc, roleGroup.desc) &&
        Objects.equals(this.userLevel, roleGroup.userLevel) &&
        Objects.equals(this.active, roleGroup.active) &&
        Objects.equals(this.roleList, roleGroup.roleList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, name, desc, userLevel, active, roleList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RoleGroup {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    desc: ").append(toIndentedString(desc)).append("\n");
    sb.append("    userLevel: ").append(toIndentedString(userLevel)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    roleList: ").append(toIndentedString(roleList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

