/*
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * ScrapingCode
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-06-18T15:11:40.792001100+09:00[Asia/Seoul]")
public class ScrapingCode {
  public static final String SERIALIZED_NAME_SERVICE_ID = "serviceId";
  @SerializedName(SERIALIZED_NAME_SERVICE_ID)
  private BigDecimal serviceId;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  private String version;

  public static final String SERIALIZED_NAME_PROVIDER_TYPE = "providerType";
  @SerializedName(SERIALIZED_NAME_PROVIDER_TYPE)
  private String providerType;

  public static final String SERIALIZED_NAME_CODE_PATH = "codePath";
  @SerializedName(SERIALIZED_NAME_CODE_PATH)
  private String codePath;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private String createdAt;

  public static final String SERIALIZED_NAME_ACTIVE = "active";
  @SerializedName(SERIALIZED_NAME_ACTIVE)
  private Boolean active;


  public ScrapingCode serviceId(BigDecimal serviceId) {
    
    this.serviceId = serviceId;
    return this;
  }

   /**
   * 서비스 번호
   * @return serviceId
  **/
  @ApiModelProperty(required = true, value = "서비스 번호")

  public BigDecimal getServiceId() {
    return serviceId;
  }


  public void setServiceId(BigDecimal serviceId) {
    this.serviceId = serviceId;
  }


  public ScrapingCode version(String version) {
    
    this.version = version;
    return this;
  }

   /**
   * 코드 버전
   * @return version
  **/
  @ApiModelProperty(required = true, value = "코드 버전")

  public String getVersion() {
    return version;
  }


  public void setVersion(String version) {
    this.version = version;
  }


  public ScrapingCode providerType(String providerType) {
    
    this.providerType = providerType;
    return this;
  }

   /**
   * 제공 서비스타입
   * @return providerType
  **/
  @ApiModelProperty(required = true, value = "제공 서비스타입")

  public String getProviderType() {
    return providerType;
  }


  public void setProviderType(String providerType) {
    this.providerType = providerType;
  }


  public ScrapingCode codePath(String codePath) {
    
    this.codePath = codePath;
    return this;
  }

   /**
   * 코드 s3 경로
   * @return codePath
  **/
  @ApiModelProperty(required = true, value = "코드 s3 경로")

  public String getCodePath() {
    return codePath;
  }


  public void setCodePath(String codePath) {
    this.codePath = codePath;
  }


  public ScrapingCode createdAt(String createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * 생성일
   * @return createdAt
  **/
  @ApiModelProperty(required = true, value = "생성일")

  public String getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }


  public ScrapingCode active(Boolean active) {
    
    this.active = active;
    return this;
  }

   /**
   * 활성여부
   * @return active
  **/
  @ApiModelProperty(required = true, value = "활성여부")

  public Boolean getActive() {
    return active;
  }


  public void setActive(Boolean active) {
    this.active = active;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScrapingCode scrapingCode = (ScrapingCode) o;
    return Objects.equals(this.serviceId, scrapingCode.serviceId) &&
        Objects.equals(this.version, scrapingCode.version) &&
        Objects.equals(this.providerType, scrapingCode.providerType) &&
        Objects.equals(this.codePath, scrapingCode.codePath) &&
        Objects.equals(this.createdAt, scrapingCode.createdAt) &&
        Objects.equals(this.active, scrapingCode.active);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serviceId, version, providerType, codePath, createdAt, active);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScrapingCode {\n");
    sb.append("    serviceId: ").append(toIndentedString(serviceId)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    providerType: ").append(toIndentedString(providerType)).append("\n");
    sb.append("    codePath: ").append(toIndentedString(codePath)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

