/*
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.Jangbu;

/**
 * SendChargeJangbuMailTestOutput
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-06-18T15:11:40.792001100+09:00[Asia/Seoul]")
public class SendChargeJangbuMailTestOutput {
  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  private String email;

  public static final String SERIALIZED_NAME_JANGBU = "jangbu";
  @SerializedName(SERIALIZED_NAME_JANGBU)
  private Jangbu jangbu;


  public SendChargeJangbuMailTestOutput email(String email) {
    
    this.email = email;
    return this;
  }

   /**
   * 수신자 이메일
   * @return email
  **/
  @ApiModelProperty(required = true, value = "수신자 이메일")

  public String getEmail() {
    return email;
  }


  public void setEmail(String email) {
    this.email = email;
  }


  public SendChargeJangbuMailTestOutput jangbu(Jangbu jangbu) {
    
    this.jangbu = jangbu;
    return this;
  }

   /**
   * 장부사
   * @return jangbu
  **/
  @ApiModelProperty(required = true, value = "장부사")

  public Jangbu getJangbu() {
    return jangbu;
  }


  public void setJangbu(Jangbu jangbu) {
    this.jangbu = jangbu;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SendChargeJangbuMailTestOutput sendChargeJangbuMailTestOutput = (SendChargeJangbuMailTestOutput) o;
    return Objects.equals(this.email, sendChargeJangbuMailTestOutput.email) &&
        Objects.equals(this.jangbu, sendChargeJangbuMailTestOutput.jangbu);
  }

  @Override
  public int hashCode() {
    return Objects.hash(email, jangbu);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SendChargeJangbuMailTestOutput {\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    jangbu: ").append(toIndentedString(jangbu)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

