/*
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SlipSplitDeleteUploadSlip
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-06-18T15:11:40.792001100+09:00[Asia/Seoul]")
public class SlipSplitDeleteUploadSlip {
  public static final String SERIALIZED_NAME_B_I_L_L_D_A_T_E = "BILL_DATE";
  @SerializedName(SERIALIZED_NAME_B_I_L_L_D_A_T_E)
  private String BILL_DATE;

  public static final String SERIALIZED_NAME_B_I_L_L_O_R_D_E_R_D_A_T_E = "BILL_ORDER_DATE";
  @SerializedName(SERIALIZED_NAME_B_I_L_L_O_R_D_E_R_D_A_T_E)
  private String BILL_ORDER_DATE;

  public static final String SERIALIZED_NAME_E_S_T_I_C_O_D_E = "ESTI_CODE";
  @SerializedName(SERIALIZED_NAME_E_S_T_I_C_O_D_E)
  private String ESTI_CODE;

  public static final String SERIALIZED_NAME_E_S_T_I_I_N_O_U_T = "ESTI_INOUT";
  @SerializedName(SERIALIZED_NAME_E_S_T_I_I_N_O_U_T)
  private String ESTI_INOUT;

  public static final String SERIALIZED_NAME_B_I_L_L_M_O_N_E_Y = "BILL_MONEY";
  @SerializedName(SERIALIZED_NAME_B_I_L_L_M_O_N_E_Y)
  private String BILL_MONEY;

  public static final String SERIALIZED_NAME_B_I_L_L_M_E_M_O = "BILL_MEMO";
  @SerializedName(SERIALIZED_NAME_B_I_L_L_M_E_M_O)
  private String BILL_MEMO;

  public static final String SERIALIZED_NAME_B_I_L_L_B_I_G_O = "BILL_BIGO";
  @SerializedName(SERIALIZED_NAME_B_I_L_L_B_I_G_O)
  private String BILL_BIGO;

  public static final String SERIALIZED_NAME_B_I_L_L_S_U_P_P_O_R_T_A_T = "BILL_SUPPORT_AT";
  @SerializedName(SERIALIZED_NAME_B_I_L_L_S_U_P_P_O_R_T_A_T)
  private String BILL_SUPPORT_AT;

  public static final String SERIALIZED_NAME_B_I_L_L_N_U_R_I_A_T = "BILL_NURI_AT";
  @SerializedName(SERIALIZED_NAME_B_I_L_L_N_U_R_I_A_T)
  private String BILL_NURI_AT;

  public static final String SERIALIZED_NAME_S_E_T_L_E_M_T_H_D = "SETLE_MTHD";
  @SerializedName(SERIALIZED_NAME_S_E_T_L_E_M_T_H_D)
  private String SETLE_MTHD;

  public static final String SERIALIZED_NAME_E_S_T_I_I_D_X = "ESTI_IDX";
  @SerializedName(SERIALIZED_NAME_E_S_T_I_I_D_X)
  private String ESTI_IDX;

  public static final String SERIALIZED_NAME_E_S_T_I_N_A_M_E = "ESTI_NAME";
  @SerializedName(SERIALIZED_NAME_E_S_T_I_N_A_M_E)
  private String ESTI_NAME;

  public static final String SERIALIZED_NAME_E_S_T_I_D_E_P_T_H = "ESTI_DEPTH";
  @SerializedName(SERIALIZED_NAME_E_S_T_I_D_E_P_T_H)
  private String ESTI_DEPTH;

  public static final String SERIALIZED_NAME_E_S_T_I_N_A_M_E1 = "ESTI_NAME_1";
  @SerializedName(SERIALIZED_NAME_E_S_T_I_N_A_M_E1)
  private String ESTI_NAME_1;

  public static final String SERIALIZED_NAME_E_S_T_I_N_A_M_E2 = "ESTI_NAME_2";
  @SerializedName(SERIALIZED_NAME_E_S_T_I_N_A_M_E2)
  private String ESTI_NAME_2;

  public static final String SERIALIZED_NAME_E_S_T_I_N_A_M_E3 = "ESTI_NAME_3";
  @SerializedName(SERIALIZED_NAME_E_S_T_I_N_A_M_E3)
  private String ESTI_NAME_3;


  public SlipSplitDeleteUploadSlip BILL_DATE(String BILL_DATE) {
    
    this.BILL_DATE = BILL_DATE;
    return this;
  }

   /**
   * 일자(YYYYMMDD)
   * @return BILL_DATE
  **/
  @ApiModelProperty(required = true, value = "일자(YYYYMMDD)")

  public String getBILLDATE() {
    return BILL_DATE;
  }


  public void setBILLDATE(String BILL_DATE) {
    this.BILL_DATE = BILL_DATE;
  }


  public SlipSplitDeleteUploadSlip BILL_ORDER_DATE(String BILL_ORDER_DATE) {
    
    this.BILL_ORDER_DATE = BILL_ORDER_DATE;
    return this;
  }

   /**
   * Get BILL_ORDER_DATE
   * @return BILL_ORDER_DATE
  **/
  @ApiModelProperty(required = true, value = "")

  public String getBILLORDERDATE() {
    return BILL_ORDER_DATE;
  }


  public void setBILLORDERDATE(String BILL_ORDER_DATE) {
    this.BILL_ORDER_DATE = BILL_ORDER_DATE;
  }


  public SlipSplitDeleteUploadSlip ESTI_CODE(String ESTI_CODE) {
    
    this.ESTI_CODE = ESTI_CODE;
    return this;
  }

   /**
   * 과목코드
   * @return ESTI_CODE
  **/
  @ApiModelProperty(required = true, value = "과목코드")

  public String getESTICODE() {
    return ESTI_CODE;
  }


  public void setESTICODE(String ESTI_CODE) {
    this.ESTI_CODE = ESTI_CODE;
  }


  public SlipSplitDeleteUploadSlip ESTI_INOUT(String ESTI_INOUT) {
    
    this.ESTI_INOUT = ESTI_INOUT;
    return this;
  }

   /**
   * 입출구분(I:세입, O:세출)
   * @return ESTI_INOUT
  **/
  @ApiModelProperty(required = true, value = "입출구분(I:세입, O:세출)")

  public String getESTIINOUT() {
    return ESTI_INOUT;
  }


  public void setESTIINOUT(String ESTI_INOUT) {
    this.ESTI_INOUT = ESTI_INOUT;
  }


  public SlipSplitDeleteUploadSlip BILL_MONEY(String BILL_MONEY) {
    
    this.BILL_MONEY = BILL_MONEY;
    return this;
  }

   /**
   * Get BILL_MONEY
   * @return BILL_MONEY
  **/
  @ApiModelProperty(required = true, value = "")

  public String getBILLMONEY() {
    return BILL_MONEY;
  }


  public void setBILLMONEY(String BILL_MONEY) {
    this.BILL_MONEY = BILL_MONEY;
  }


  public SlipSplitDeleteUploadSlip BILL_MEMO(String BILL_MEMO) {
    
    this.BILL_MEMO = BILL_MEMO;
    return this;
  }

   /**
   * 전표메모(공란)
   * @return BILL_MEMO
  **/
  @ApiModelProperty(required = true, value = "전표메모(공란)")

  public String getBILLMEMO() {
    return BILL_MEMO;
  }


  public void setBILLMEMO(String BILL_MEMO) {
    this.BILL_MEMO = BILL_MEMO;
  }


  public SlipSplitDeleteUploadSlip BILL_BIGO(String BILL_BIGO) {
    
    this.BILL_BIGO = BILL_BIGO;
    return this;
  }

   /**
   * 비고내용
   * @return BILL_BIGO
  **/
  @ApiModelProperty(required = true, value = "비고내용")

  public String getBILLBIGO() {
    return BILL_BIGO;
  }


  public void setBILLBIGO(String BILL_BIGO) {
    this.BILL_BIGO = BILL_BIGO;
  }


  public SlipSplitDeleteUploadSlip BILL_SUPPORT_AT(String BILL_SUPPORT_AT) {
    
    this.BILL_SUPPORT_AT = BILL_SUPPORT_AT;
    return this;
  }

   /**
   * Get BILL_SUPPORT_AT
   * @return BILL_SUPPORT_AT
  **/
  @ApiModelProperty(required = true, value = "")

  public String getBILLSUPPORTAT() {
    return BILL_SUPPORT_AT;
  }


  public void setBILLSUPPORTAT(String BILL_SUPPORT_AT) {
    this.BILL_SUPPORT_AT = BILL_SUPPORT_AT;
  }


  public SlipSplitDeleteUploadSlip BILL_NURI_AT(String BILL_NURI_AT) {
    
    this.BILL_NURI_AT = BILL_NURI_AT;
    return this;
  }

   /**
   * Get BILL_NURI_AT
   * @return BILL_NURI_AT
  **/
  @ApiModelProperty(required = true, value = "")

  public String getBILLNURIAT() {
    return BILL_NURI_AT;
  }


  public void setBILLNURIAT(String BILL_NURI_AT) {
    this.BILL_NURI_AT = BILL_NURI_AT;
  }


  public SlipSplitDeleteUploadSlip SETLE_MTHD(String SETLE_MTHD) {
    
    this.SETLE_MTHD = SETLE_MTHD;
    return this;
  }

   /**
   * Get SETLE_MTHD
   * @return SETLE_MTHD
  **/
  @ApiModelProperty(required = true, value = "")

  public String getSETLEMTHD() {
    return SETLE_MTHD;
  }


  public void setSETLEMTHD(String SETLE_MTHD) {
    this.SETLE_MTHD = SETLE_MTHD;
  }


  public SlipSplitDeleteUploadSlip ESTI_IDX(String ESTI_IDX) {
    
    this.ESTI_IDX = ESTI_IDX;
    return this;
  }

   /**
   * Get ESTI_IDX
   * @return ESTI_IDX
  **/
  @ApiModelProperty(required = true, value = "")

  public String getESTIIDX() {
    return ESTI_IDX;
  }


  public void setESTIIDX(String ESTI_IDX) {
    this.ESTI_IDX = ESTI_IDX;
  }


  public SlipSplitDeleteUploadSlip ESTI_NAME(String ESTI_NAME) {
    
    this.ESTI_NAME = ESTI_NAME;
    return this;
  }

   /**
   * Get ESTI_NAME
   * @return ESTI_NAME
  **/
  @ApiModelProperty(required = true, value = "")

  public String getESTINAME() {
    return ESTI_NAME;
  }


  public void setESTINAME(String ESTI_NAME) {
    this.ESTI_NAME = ESTI_NAME;
  }


  public SlipSplitDeleteUploadSlip ESTI_DEPTH(String ESTI_DEPTH) {
    
    this.ESTI_DEPTH = ESTI_DEPTH;
    return this;
  }

   /**
   * Get ESTI_DEPTH
   * @return ESTI_DEPTH
  **/
  @ApiModelProperty(required = true, value = "")

  public String getESTIDEPTH() {
    return ESTI_DEPTH;
  }


  public void setESTIDEPTH(String ESTI_DEPTH) {
    this.ESTI_DEPTH = ESTI_DEPTH;
  }


  public SlipSplitDeleteUploadSlip ESTI_NAME_1(String ESTI_NAME_1) {
    
    this.ESTI_NAME_1 = ESTI_NAME_1;
    return this;
  }

   /**
   * Get ESTI_NAME_1
   * @return ESTI_NAME_1
  **/
  @ApiModelProperty(required = true, value = "")

  public String getESTINAME1() {
    return ESTI_NAME_1;
  }


  public void setESTINAME1(String ESTI_NAME_1) {
    this.ESTI_NAME_1 = ESTI_NAME_1;
  }


  public SlipSplitDeleteUploadSlip ESTI_NAME_2(String ESTI_NAME_2) {
    
    this.ESTI_NAME_2 = ESTI_NAME_2;
    return this;
  }

   /**
   * Get ESTI_NAME_2
   * @return ESTI_NAME_2
  **/
  @ApiModelProperty(required = true, value = "")

  public String getESTINAME2() {
    return ESTI_NAME_2;
  }


  public void setESTINAME2(String ESTI_NAME_2) {
    this.ESTI_NAME_2 = ESTI_NAME_2;
  }


  public SlipSplitDeleteUploadSlip ESTI_NAME_3(String ESTI_NAME_3) {
    
    this.ESTI_NAME_3 = ESTI_NAME_3;
    return this;
  }

   /**
   * Get ESTI_NAME_3
   * @return ESTI_NAME_3
  **/
  @ApiModelProperty(required = true, value = "")

  public String getESTINAME3() {
    return ESTI_NAME_3;
  }


  public void setESTINAME3(String ESTI_NAME_3) {
    this.ESTI_NAME_3 = ESTI_NAME_3;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SlipSplitDeleteUploadSlip slipSplitDeleteUploadSlip = (SlipSplitDeleteUploadSlip) o;
    return Objects.equals(this.BILL_DATE, slipSplitDeleteUploadSlip.BILL_DATE) &&
        Objects.equals(this.BILL_ORDER_DATE, slipSplitDeleteUploadSlip.BILL_ORDER_DATE) &&
        Objects.equals(this.ESTI_CODE, slipSplitDeleteUploadSlip.ESTI_CODE) &&
        Objects.equals(this.ESTI_INOUT, slipSplitDeleteUploadSlip.ESTI_INOUT) &&
        Objects.equals(this.BILL_MONEY, slipSplitDeleteUploadSlip.BILL_MONEY) &&
        Objects.equals(this.BILL_MEMO, slipSplitDeleteUploadSlip.BILL_MEMO) &&
        Objects.equals(this.BILL_BIGO, slipSplitDeleteUploadSlip.BILL_BIGO) &&
        Objects.equals(this.BILL_SUPPORT_AT, slipSplitDeleteUploadSlip.BILL_SUPPORT_AT) &&
        Objects.equals(this.BILL_NURI_AT, slipSplitDeleteUploadSlip.BILL_NURI_AT) &&
        Objects.equals(this.SETLE_MTHD, slipSplitDeleteUploadSlip.SETLE_MTHD) &&
        Objects.equals(this.ESTI_IDX, slipSplitDeleteUploadSlip.ESTI_IDX) &&
        Objects.equals(this.ESTI_NAME, slipSplitDeleteUploadSlip.ESTI_NAME) &&
        Objects.equals(this.ESTI_DEPTH, slipSplitDeleteUploadSlip.ESTI_DEPTH) &&
        Objects.equals(this.ESTI_NAME_1, slipSplitDeleteUploadSlip.ESTI_NAME_1) &&
        Objects.equals(this.ESTI_NAME_2, slipSplitDeleteUploadSlip.ESTI_NAME_2) &&
        Objects.equals(this.ESTI_NAME_3, slipSplitDeleteUploadSlip.ESTI_NAME_3);
  }

  @Override
  public int hashCode() {
    return Objects.hash(BILL_DATE, BILL_ORDER_DATE, ESTI_CODE, ESTI_INOUT, BILL_MONEY, BILL_MEMO, BILL_BIGO, BILL_SUPPORT_AT, BILL_NURI_AT, SETLE_MTHD, ESTI_IDX, ESTI_NAME, ESTI_DEPTH, ESTI_NAME_1, ESTI_NAME_2, ESTI_NAME_3);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SlipSplitDeleteUploadSlip {\n");
    sb.append("    BILL_DATE: ").append(toIndentedString(BILL_DATE)).append("\n");
    sb.append("    BILL_ORDER_DATE: ").append(toIndentedString(BILL_ORDER_DATE)).append("\n");
    sb.append("    ESTI_CODE: ").append(toIndentedString(ESTI_CODE)).append("\n");
    sb.append("    ESTI_INOUT: ").append(toIndentedString(ESTI_INOUT)).append("\n");
    sb.append("    BILL_MONEY: ").append(toIndentedString(BILL_MONEY)).append("\n");
    sb.append("    BILL_MEMO: ").append(toIndentedString(BILL_MEMO)).append("\n");
    sb.append("    BILL_BIGO: ").append(toIndentedString(BILL_BIGO)).append("\n");
    sb.append("    BILL_SUPPORT_AT: ").append(toIndentedString(BILL_SUPPORT_AT)).append("\n");
    sb.append("    BILL_NURI_AT: ").append(toIndentedString(BILL_NURI_AT)).append("\n");
    sb.append("    SETLE_MTHD: ").append(toIndentedString(SETLE_MTHD)).append("\n");
    sb.append("    ESTI_IDX: ").append(toIndentedString(ESTI_IDX)).append("\n");
    sb.append("    ESTI_NAME: ").append(toIndentedString(ESTI_NAME)).append("\n");
    sb.append("    ESTI_DEPTH: ").append(toIndentedString(ESTI_DEPTH)).append("\n");
    sb.append("    ESTI_NAME_1: ").append(toIndentedString(ESTI_NAME_1)).append("\n");
    sb.append("    ESTI_NAME_2: ").append(toIndentedString(ESTI_NAME_2)).append("\n");
    sb.append("    ESTI_NAME_3: ").append(toIndentedString(ESTI_NAME_3)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

