/*
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * UpdateChargeJangbuPartnershipInput
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-06-18T15:11:40.792001100+09:00[Asia/Seoul]")
public class UpdateChargeJangbuPartnershipInput {
  public static final String SERIALIZED_NAME_APPLY_COUNT = "applyCount";
  @SerializedName(SERIALIZED_NAME_APPLY_COUNT)
  private BigDecimal applyCount;

  public static final String SERIALIZED_NAME_UNIT_PRICE = "unitPrice";
  @SerializedName(SERIALIZED_NAME_UNIT_PRICE)
  private BigDecimal unitPrice;


  public UpdateChargeJangbuPartnershipInput applyCount(BigDecimal applyCount) {
    
    this.applyCount = applyCount;
    return this;
  }

   /**
   * 계좌수
   * @return applyCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "계좌수")

  public BigDecimal getApplyCount() {
    return applyCount;
  }


  public void setApplyCount(BigDecimal applyCount) {
    this.applyCount = applyCount;
  }


  public UpdateChargeJangbuPartnershipInput unitPrice(BigDecimal unitPrice) {
    
    this.unitPrice = unitPrice;
    return this;
  }

   /**
   * 단가
   * @return unitPrice
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "단가")

  public BigDecimal getUnitPrice() {
    return unitPrice;
  }


  public void setUnitPrice(BigDecimal unitPrice) {
    this.unitPrice = unitPrice;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateChargeJangbuPartnershipInput updateChargeJangbuPartnershipInput = (UpdateChargeJangbuPartnershipInput) o;
    return Objects.equals(this.applyCount, updateChargeJangbuPartnershipInput.applyCount) &&
        Objects.equals(this.unitPrice, updateChargeJangbuPartnershipInput.unitPrice);
  }

  @Override
  public int hashCode() {
    return Objects.hash(applyCount, unitPrice);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateChargeJangbuPartnershipInput {\n");
    sb.append("    applyCount: ").append(toIndentedString(applyCount)).append("\n");
    sb.append("    unitPrice: ").append(toIndentedString(unitPrice)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

