/*
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.RoleGroupMapping;

/**
 * UpdateRoleGroupInput
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-06-18T15:11:40.792001100+09:00[Asia/Seoul]")
public class UpdateRoleGroupInput {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_DESC = "desc";
  @SerializedName(SERIALIZED_NAME_DESC)
  private String desc;

  public static final String SERIALIZED_NAME_ROLES = "roles";
  @SerializedName(SERIALIZED_NAME_ROLES)
  private List<RoleGroupMapping> roles = new ArrayList<RoleGroupMapping>();

  public static final String SERIALIZED_NAME_ACTIVE = "active";
  @SerializedName(SERIALIZED_NAME_ACTIVE)
  private Boolean active;


  public UpdateRoleGroupInput name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * 권한그룹명
   * @return name
  **/
  @ApiModelProperty(required = true, value = "권한그룹명")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public UpdateRoleGroupInput desc(String desc) {
    
    this.desc = desc;
    return this;
  }

   /**
   * 권한그룹 설명
   * @return desc
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "권한그룹 설명")

  public String getDesc() {
    return desc;
  }


  public void setDesc(String desc) {
    this.desc = desc;
  }


  public UpdateRoleGroupInput roles(List<RoleGroupMapping> roles) {
    
    this.roles = roles;
    return this;
  }

  public UpdateRoleGroupInput addRolesItem(RoleGroupMapping rolesItem) {
    this.roles.add(rolesItem);
    return this;
  }

   /**
   * 권한 이름과 접근 권한 목록
   * @return roles
  **/
  @ApiModelProperty(required = true, value = "권한 이름과 접근 권한 목록")

  public List<RoleGroupMapping> getRoles() {
    return roles;
  }


  public void setRoles(List<RoleGroupMapping> roles) {
    this.roles = roles;
  }


  public UpdateRoleGroupInput active(Boolean active) {
    
    this.active = active;
    return this;
  }

   /**
   * 활성 여부
   * @return active
  **/
  @ApiModelProperty(required = true, value = "활성 여부")

  public Boolean getActive() {
    return active;
  }


  public void setActive(Boolean active) {
    this.active = active;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateRoleGroupInput updateRoleGroupInput = (UpdateRoleGroupInput) o;
    return Objects.equals(this.name, updateRoleGroupInput.name) &&
        Objects.equals(this.desc, updateRoleGroupInput.desc) &&
        Objects.equals(this.roles, updateRoleGroupInput.roles) &&
        Objects.equals(this.active, updateRoleGroupInput.active);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, desc, roles, active);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateRoleGroupInput {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    desc: ").append(toIndentedString(desc)).append("\n");
    sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

