/*
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * WorkResultDetail
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-06-18T15:11:40.792001100+09:00[Asia/Seoul]")
public class WorkResultDetail {
  public static final String SERIALIZED_NAME_SUCCESS_COUNT = "successCount";
  @SerializedName(SERIALIZED_NAME_SUCCESS_COUNT)
  private BigDecimal successCount;

  public static final String SERIALIZED_NAME_FAIL_COUNT = "failCount";
  @SerializedName(SERIALIZED_NAME_FAIL_COUNT)
  private BigDecimal failCount;

  public static final String SERIALIZED_NAME_RESULT_MESSAGE = "resultMessage";
  @SerializedName(SERIALIZED_NAME_RESULT_MESSAGE)
  private String resultMessage;

  public static final String SERIALIZED_NAME_RESULT_PATH = "resultPath";
  @SerializedName(SERIALIZED_NAME_RESULT_PATH)
  private String resultPath;


  public WorkResultDetail successCount(BigDecimal successCount) {
    
    this.successCount = successCount;
    return this;
  }

   /**
   * 성공건수
   * @return successCount
  **/
  @ApiModelProperty(required = true, value = "성공건수")

  public BigDecimal getSuccessCount() {
    return successCount;
  }


  public void setSuccessCount(BigDecimal successCount) {
    this.successCount = successCount;
  }


  public WorkResultDetail failCount(BigDecimal failCount) {
    
    this.failCount = failCount;
    return this;
  }

   /**
   * 실패건수
   * @return failCount
  **/
  @ApiModelProperty(required = true, value = "실패건수")

  public BigDecimal getFailCount() {
    return failCount;
  }


  public void setFailCount(BigDecimal failCount) {
    this.failCount = failCount;
  }


  public WorkResultDetail resultMessage(String resultMessage) {
    
    this.resultMessage = resultMessage;
    return this;
  }

   /**
   * 스크래핑결과 내용
   * @return resultMessage
  **/
  @ApiModelProperty(required = true, value = "스크래핑결과 내용")

  public String getResultMessage() {
    return resultMessage;
  }


  public void setResultMessage(String resultMessage) {
    this.resultMessage = resultMessage;
  }


  public WorkResultDetail resultPath(String resultPath) {
    
    this.resultPath = resultPath;
    return this;
  }

   /**
   * 스크래핑 결과 S3경로
   * @return resultPath
  **/
  @ApiModelProperty(required = true, value = "스크래핑 결과 S3경로")

  public String getResultPath() {
    return resultPath;
  }


  public void setResultPath(String resultPath) {
    this.resultPath = resultPath;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkResultDetail workResultDetail = (WorkResultDetail) o;
    return Objects.equals(this.successCount, workResultDetail.successCount) &&
        Objects.equals(this.failCount, workResultDetail.failCount) &&
        Objects.equals(this.resultMessage, workResultDetail.resultMessage) &&
        Objects.equals(this.resultPath, workResultDetail.resultPath);
  }

  @Override
  public int hashCode() {
    return Objects.hash(successCount, failCount, resultMessage, resultPath);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkResultDetail {\n");
    sb.append("    successCount: ").append(toIndentedString(successCount)).append("\n");
    sb.append("    failCount: ").append(toIndentedString(failCount)).append("\n");
    sb.append("    resultMessage: ").append(toIndentedString(resultMessage)).append("\n");
    sb.append("    resultPath: ").append(toIndentedString(resultPath)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

