/*
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.openapitools.client.model.Jangbu;
import org.openapitools.client.model.ProcessFlag;
import org.openapitools.client.model.User;
import org.openapitools.client.model.WorkDetail;
import org.openapitools.client.model.WorkResult;
import org.threeten.bp.OffsetDateTime;

/**
 * Work
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-06-18T15:11:40.792001100+09:00[Asia/Seoul]")
public class Work {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private BigDecimal id;

  public static final String SERIALIZED_NAME_SERVICE_ID = "serviceId";
  @SerializedName(SERIALIZED_NAME_SERVICE_ID)
  private BigDecimal serviceId;

  public static final String SERIALIZED_NAME_USER_ID = "userId";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private BigDecimal userId;

  public static final String SERIALIZED_NAME_JANGBU_ID = "jangbuId";
  @SerializedName(SERIALIZED_NAME_JANGBU_ID)
  private BigDecimal jangbuId;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private ProcessFlag status;

  public static final String SERIALIZED_NAME_API_ID = "apiId";
  @SerializedName(SERIALIZED_NAME_API_ID)
  private BigDecimal apiId;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_WORK_DETAIL = "workDetail";
  @SerializedName(SERIALIZED_NAME_WORK_DETAIL)
  private WorkDetail workDetail;

  public static final String SERIALIZED_NAME_USER = "user";
  @SerializedName(SERIALIZED_NAME_USER)
  private User user;

  public static final String SERIALIZED_NAME_JANGBU = "jangbu";
  @SerializedName(SERIALIZED_NAME_JANGBU)
  private Jangbu jangbu;

  public static final String SERIALIZED_NAME_WORK_RESULT = "workResult";
  @SerializedName(SERIALIZED_NAME_WORK_RESULT)
  private WorkResult workResult;


  public Work id(BigDecimal id) {
    
    this.id = id;
    return this;
  }

   /**
   * 업무 순번
   * @return id
  **/
  @ApiModelProperty(required = true, value = "업무 순번")

  public BigDecimal getId() {
    return id;
  }


  public void setId(BigDecimal id) {
    this.id = id;
  }


  public Work serviceId(BigDecimal serviceId) {
    
    this.serviceId = serviceId;
    return this;
  }

   /**
   * 서비스 순번
   * @return serviceId
  **/
  @ApiModelProperty(required = true, value = "서비스 순번")

  public BigDecimal getServiceId() {
    return serviceId;
  }


  public void setServiceId(BigDecimal serviceId) {
    this.serviceId = serviceId;
  }


  public Work userId(BigDecimal userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * 회원 순번
   * @return userId
  **/
  @ApiModelProperty(required = true, value = "회원 순번")

  public BigDecimal getUserId() {
    return userId;
  }


  public void setUserId(BigDecimal userId) {
    this.userId = userId;
  }


  public Work jangbuId(BigDecimal jangbuId) {
    
    this.jangbuId = jangbuId;
    return this;
  }

   /**
   * 장부사 순번
   * @return jangbuId
  **/
  @ApiModelProperty(required = true, value = "장부사 순번")

  public BigDecimal getJangbuId() {
    return jangbuId;
  }


  public void setJangbuId(BigDecimal jangbuId) {
    this.jangbuId = jangbuId;
  }


  public Work status(ProcessFlag status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(required = true, value = "")

  public ProcessFlag getStatus() {
    return status;
  }


  public void setStatus(ProcessFlag status) {
    this.status = status;
  }


  public Work apiId(BigDecimal apiId) {
    
    this.apiId = apiId;
    return this;
  }

   /**
   * api 순번
   * @return apiId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "api 순번")

  public BigDecimal getApiId() {
    return apiId;
  }


  public void setApiId(BigDecimal apiId) {
    this.apiId = apiId;
  }


  public Work createdAt(OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * 생성일
   * @return createdAt
  **/
  @ApiModelProperty(required = true, value = "생성일")

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public Work workDetail(WorkDetail workDetail) {
    
    this.workDetail = workDetail;
    return this;
  }

   /**
   * 업무 상세정보
   * @return workDetail
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "업무 상세정보")

  public WorkDetail getWorkDetail() {
    return workDetail;
  }


  public void setWorkDetail(WorkDetail workDetail) {
    this.workDetail = workDetail;
  }


  public Work user(User user) {
    
    this.user = user;
    return this;
  }

   /**
   * 회원정보
   * @return user
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "회원정보")

  public User getUser() {
    return user;
  }


  public void setUser(User user) {
    this.user = user;
  }


  public Work jangbu(Jangbu jangbu) {
    
    this.jangbu = jangbu;
    return this;
  }

   /**
   * 장부사정보
   * @return jangbu
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "장부사정보")

  public Jangbu getJangbu() {
    return jangbu;
  }


  public void setJangbu(Jangbu jangbu) {
    this.jangbu = jangbu;
  }


  public Work workResult(WorkResult workResult) {
    
    this.workResult = workResult;
    return this;
  }

   /**
   * 스크래핑 결과
   * @return workResult
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "스크래핑 결과")

  public WorkResult getWorkResult() {
    return workResult;
  }


  public void setWorkResult(WorkResult workResult) {
    this.workResult = workResult;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Work work = (Work) o;
    return Objects.equals(this.id, work.id) &&
        Objects.equals(this.serviceId, work.serviceId) &&
        Objects.equals(this.userId, work.userId) &&
        Objects.equals(this.jangbuId, work.jangbuId) &&
        Objects.equals(this.status, work.status) &&
        Objects.equals(this.apiId, work.apiId) &&
        Objects.equals(this.createdAt, work.createdAt) &&
        Objects.equals(this.workDetail, work.workDetail) &&
        Objects.equals(this.user, work.user) &&
        Objects.equals(this.jangbu, work.jangbu) &&
        Objects.equals(this.workResult, work.workResult);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, serviceId, userId, jangbuId, status, apiId, createdAt, workDetail, user, jangbu, workResult);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Work {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    serviceId: ").append(toIndentedString(serviceId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    jangbuId: ").append(toIndentedString(jangbuId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    apiId: ").append(toIndentedString(apiId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    workDetail: ").append(toIndentedString(workDetail)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    jangbu: ").append(toIndentedString(jangbu)).append("\n");
    sb.append("    workResult: ").append(toIndentedString(workResult)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

