/**
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ChargeJangbuPartnership } from './chargeJangbuPartnership';

export class Jangbu {
    /**
    * 장부사번호
    */
    'id': number;
    /**
    * 장부사 아이디
    */
    'repId': string;
    /**
    * 유효성여부
    */
    'active': boolean;
    /**
    * 장부사명
    */
    'name': string;
    /**
    * 과금 이메일
    */
    'taxEmail': string;
    /**
    * 생성일자
    */
    'createdAt': Date;
    /**
    * 계좌통합서비스 정보목록
    */
    'chargeJangbuPartnerships'?: Array<ChargeJangbuPartnership> | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "repId",
            "baseName": "repId",
            "type": "string"
        },
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "taxEmail",
            "baseName": "taxEmail",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "chargeJangbuPartnerships",
            "baseName": "chargeJangbuPartnerships",
            "type": "Array<ChargeJangbuPartnership>"
        }    ];

    static getAttributeTypeMap() {
        return Jangbu.attributeTypeMap;
    }
}

