/**
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Notice {
    /**
    * 공지사항 순번
    */
    'id': number;
    /**
    * 공지사항 제목
    */
    'title': string;
    /**
    * 공지사항 내용
    */
    'content': string;
    /**
    * 공지사항 조회수
    */
    'count': number;
    /**
    * 공개범위
    */
    'partner': Notice.PartnerEnum;
    /**
    * 공지사항 생성일
    */
    'createdAt': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "string"
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number"
        },
        {
            "name": "partner",
            "baseName": "partner",
            "type": "Notice.PartnerEnum"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return Notice.attributeTypeMap;
    }
}

export namespace Notice {
    export enum PartnerEnum {
         = <any> '전체',
         = <any> '뱅크다',
        _24 = <any> '카페24'
    }
}
