/**
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class PagingLinks {
    /**
    * 처음 페이지 링크
    */
    'first'?: string;
    /**
    * 이전 페이지 링크
    */
    'previous'?: string;
    /**
    * 다음 페이지 링크
    */
    'next'?: string;
    /**
    * 마지막 페이지 링크
    */
    'last'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "first",
            "baseName": "first",
            "type": "string"
        },
        {
            "name": "previous",
            "baseName": "previous",
            "type": "string"
        },
        {
            "name": "next",
            "baseName": "next",
            "type": "string"
        },
        {
            "name": "last",
            "baseName": "last",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PagingLinks.attributeTypeMap;
    }
}

