/**
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class PcClient {
    /**
    * 클라이언트 PC의 UUID 정보
    */
    'pcId': string;
    /**
    * 클라이언트 시스템 정보(json)
    */
    'clientInfo': string;
    /**
    * 생성일자
    */
    'createdAt': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "pcId",
            "baseName": "pcId",
            "type": "string"
        },
        {
            "name": "clientInfo",
            "baseName": "clientInfo",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PcClient.attributeTypeMap;
    }
}

