/**
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AdjustJangbuService } from './adjustJangbuService';
import { ChargeJangbu } from './chargeJangbu';
import { ChargeJangbuPartnership } from './chargeJangbuPartnership';

export class RegisterAdjustOutput {
    /**
    * 진행된 정산내역 등록단계
    */
    'step': number;
    /**
    * (1단계진행시 반환정보) 장부사 서비스별 단가목록
    */
    'adjustJangbuServices'?: Array<AdjustJangbuService> | null;
    /**
    * (1단계진행시 반환정보) 장부사 계좌통합서비스 정보
    */
    'chargeJangbuPartnership'?: ChargeJangbuPartnership | null;
    /**
    * (2단계진행시 반환정보) 해당연월 장부사 정산금액
    */
    'chargeJangbu'?: ChargeJangbu | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "step",
            "baseName": "step",
            "type": "number"
        },
        {
            "name": "adjustJangbuServices",
            "baseName": "adjustJangbuServices",
            "type": "Array<AdjustJangbuService>"
        },
        {
            "name": "chargeJangbuPartnership",
            "baseName": "chargeJangbuPartnership",
            "type": "ChargeJangbuPartnership"
        },
        {
            "name": "chargeJangbu",
            "baseName": "chargeJangbu",
            "type": "ChargeJangbu"
        }    ];

    static getAttributeTypeMap() {
        return RegisterAdjustOutput.attributeTypeMap;
    }
}

