/**
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class RegisterJangbuInputDetailJangbu {
    /**
    * 장부사명
    */
    'name': string;
    /**
    * 세금계산서 이메일
    */
    'taxEmail': string;
    /**
    * 계좌통합 계산 필요 DB명
    */
    'partnershipDb'?: string | null;
    /**
    * 계좌통합 계산 필요 조회 아이디
    */
    'partnershipId'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "taxEmail",
            "baseName": "taxEmail",
            "type": "string"
        },
        {
            "name": "partnershipDb",
            "baseName": "partnershipDb",
            "type": "string"
        },
        {
            "name": "partnershipId",
            "baseName": "partnershipId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RegisterJangbuInputDetailJangbu.attributeTypeMap;
    }
}

