/**
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class RegisterMemberInput {
    /**
    * 사용자 유형
    */
    'userLevel': RegisterMemberInput.UserLevelEnum;
    /**
    * 장부사 순번 (관리자 회원의 경우에는 생략)
    */
    'jangbuId'?: number | null;
    /**
    * 로그인 아이디
    */
    'loginId': string;
    /**
    * 이름
    */
    'name': string;
    /**
    * 대표자명
    */
    'ceoName': string;
    /**
    * 이메일
    */
    'email': string;
    /**
    * 휴대폰번호
    */
    'phone': string;
    /**
    * 권한그룹코드
    */
    'roleGroupCode'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "userLevel",
            "baseName": "userLevel",
            "type": "RegisterMemberInput.UserLevelEnum"
        },
        {
            "name": "jangbuId",
            "baseName": "jangbuId",
            "type": "number"
        },
        {
            "name": "loginId",
            "baseName": "loginId",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "ceoName",
            "baseName": "ceoName",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string"
        },
        {
            "name": "roleGroupCode",
            "baseName": "roleGroupCode",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RegisterMemberInput.attributeTypeMap;
    }
}

export namespace RegisterMemberInput {
    export enum UserLevelEnum {
        NUMBER_2 = <any> 2,
        NUMBER_3 = <any> 3
    }
}
