/**
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SlipUploadVoucher } from './slipUploadVoucher';

export class SlipUpload {
    /**
    * 거래일시(YYYYMMDD)
    */
    'tRANSDATETIME': string;
    /**
    * 일자(YYYYMMDD)
    */
    'bILLDATE': string;
    /**
    * 거래일자(YYYYMMDD)
    */
    'tRANSDATE': string;
    /**
    * 과목코드
    */
    'eSTICODE': string;
    /**
    * 입출구분(I:세입, O:세출)
    */
    'eSTIINOUT': string;
    /**
    * 전표메모(공란)
    */
    'bILLMEMO': string;
    /**
    * 전표비고
    */
    'bILLBIGO': string;
    /**
    * 보조금여부(Y, N)
    */
    'bILLSUPPORTAT': string;
    /**
    * 누리지원여부(Y, N)
    */
    'bILLNURIAT': string;
    /**
    * 거래내역 입출구분 (I/O)
    */
    'tRANSGB': string;
    /**
    * 거래금액
    */
    'tRANSMONEY': string;
    /**
    * 입금액(출금거래시 0)
    */
    'tRANSMONEYIN': string;
    /**
    * 출금액(입금거래시 0)
    */
    'tRANSMONEYOUT': string;
    /**
    * 거래후 잔액
    */
    'tRANSREMAIN': string;
    /**
    * 거래내용(적요) 
    */
    'tRANSMEMO': string;
    /**
    * 결제방식(100~700)
    */
    'sETLEMTHD': string;
    /**
    * 증빙 목록
    */
    'vOUCHER'?: Array<SlipUploadVoucher> | null;
    /**
    * (slip_delete_upload의 경우 존재함)
    */
    'eSTIIDX'?: string | null;
    /**
    * (slip_delete_upload의 경우 존재함)
    */
    'eSTINAME'?: string | null;
    /**
    * (slip_delete_upload의 경우 존재함)
    */
    'eSTIDEPTH'?: string | null;
    /**
    * (slip_delete_upload의 경우 존재함)
    */
    'eSTINAME1'?: string | null;
    /**
    * (slip_delete_upload의 경우 존재함)
    */
    'eSTINAME2'?: string | null;
    /**
    * (slip_delete_upload의 경우 존재함)
    */
    'eSTINAME3'?: string | null;
    /**
    * (slip_delete_upload의 경우 존재함)
    */
    'bILLSUBCODE'?: string | null;
    /**
    * (slip_delete_upload의 경우 존재함)
    */
    'eSTIDISPLAY'?: string | null;
    /**
    * (slip_delete_upload의 경우 존재함)
    */
    'eSTIGB'?: string | null;
    /**
    * (slip_delete_upload의 경우 존재함)
    */
    'eSTIPART'?: string | null;
    /**
    * (slip_delete_upload의 경우 존재함)
    */
    'eSTISUBNM'?: string | null;
    /**
    * (slip_delete_upload의 경우 존재함)
    */
    'eSTISUBYN'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "tRANSDATETIME",
            "baseName": "TRANS_DATETIME",
            "type": "string"
        },
        {
            "name": "bILLDATE",
            "baseName": "BILL_DATE",
            "type": "string"
        },
        {
            "name": "tRANSDATE",
            "baseName": "TRANS_DATE",
            "type": "string"
        },
        {
            "name": "eSTICODE",
            "baseName": "ESTI_CODE",
            "type": "string"
        },
        {
            "name": "eSTIINOUT",
            "baseName": "ESTI_INOUT",
            "type": "string"
        },
        {
            "name": "bILLMEMO",
            "baseName": "BILL_MEMO",
            "type": "string"
        },
        {
            "name": "bILLBIGO",
            "baseName": "BILL_BIGO",
            "type": "string"
        },
        {
            "name": "bILLSUPPORTAT",
            "baseName": "BILL_SUPPORT_AT",
            "type": "string"
        },
        {
            "name": "bILLNURIAT",
            "baseName": "BILL_NURI_AT",
            "type": "string"
        },
        {
            "name": "tRANSGB",
            "baseName": "TRANS_GB",
            "type": "string"
        },
        {
            "name": "tRANSMONEY",
            "baseName": "TRANS_MONEY",
            "type": "string"
        },
        {
            "name": "tRANSMONEYIN",
            "baseName": "TRANS_MONEY_IN",
            "type": "string"
        },
        {
            "name": "tRANSMONEYOUT",
            "baseName": "TRANS_MONEY_OUT",
            "type": "string"
        },
        {
            "name": "tRANSREMAIN",
            "baseName": "TRANS_REMAIN",
            "type": "string"
        },
        {
            "name": "tRANSMEMO",
            "baseName": "TRANS_MEMO",
            "type": "string"
        },
        {
            "name": "sETLEMTHD",
            "baseName": "SETLE_MTHD",
            "type": "string"
        },
        {
            "name": "vOUCHER",
            "baseName": "VOUCHER",
            "type": "Array<SlipUploadVoucher>"
        },
        {
            "name": "eSTIIDX",
            "baseName": "ESTI_IDX",
            "type": "string"
        },
        {
            "name": "eSTINAME",
            "baseName": "ESTI_NAME",
            "type": "string"
        },
        {
            "name": "eSTIDEPTH",
            "baseName": "ESTI_DEPTH",
            "type": "string"
        },
        {
            "name": "eSTINAME1",
            "baseName": "ESTI_NAME_1",
            "type": "string"
        },
        {
            "name": "eSTINAME2",
            "baseName": "ESTI_NAME_2",
            "type": "string"
        },
        {
            "name": "eSTINAME3",
            "baseName": "ESTI_NAME_3",
            "type": "string"
        },
        {
            "name": "bILLSUBCODE",
            "baseName": "BILL_SUBCODE",
            "type": "string"
        },
        {
            "name": "eSTIDISPLAY",
            "baseName": "ESTI_DISPLAY",
            "type": "string"
        },
        {
            "name": "eSTIGB",
            "baseName": "ESTI_GB",
            "type": "string"
        },
        {
            "name": "eSTIPART",
            "baseName": "ESTI_PART",
            "type": "string"
        },
        {
            "name": "eSTISUBNM",
            "baseName": "ESTI_SUB_NM",
            "type": "string"
        },
        {
            "name": "eSTISUBYN",
            "baseName": "ESTI_SUB_YN",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SlipUpload.attributeTypeMap;
    }
}

