/**
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Jangbu } from './jangbu';
import { ProcessFlag } from './processFlag';
import { User } from './user';
import { WorkDetail } from './workDetail';
import { WorkResult } from './workResult';

export class Work {
    /**
    * 업무 순번
    */
    'id': number;
    /**
    * 서비스 순번
    */
    'serviceId': number;
    /**
    * 회원 순번
    */
    'userId': number;
    /**
    * 장부사 순번
    */
    'jangbuId': number;
    'status': ProcessFlag;
    /**
    * api 순번
    */
    'apiId'?: number | null;
    /**
    * 생성일
    */
    'createdAt': Date;
    /**
    * 업무 상세정보
    */
    'workDetail'?: WorkDetail | null;
    /**
    * 회원정보
    */
    'user'?: User | null;
    /**
    * 장부사정보
    */
    'jangbu'?: Jangbu | null;
    /**
    * 스크래핑 결과
    */
    'workResult'?: WorkResult | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "serviceId",
            "baseName": "serviceId",
            "type": "number"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "number"
        },
        {
            "name": "jangbuId",
            "baseName": "jangbuId",
            "type": "number"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "ProcessFlag"
        },
        {
            "name": "apiId",
            "baseName": "apiId",
            "type": "number"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "workDetail",
            "baseName": "workDetail",
            "type": "WorkDetail"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "User"
        },
        {
            "name": "jangbu",
            "baseName": "jangbu",
            "type": "Jangbu"
        },
        {
            "name": "workResult",
            "baseName": "workResult",
            "type": "WorkResult"
        }    ];

    static getAttributeTypeMap() {
        return Work.attributeTypeMap;
    }
}

