<?php
/**
 * DefaultApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * 뱅크다K 웹앱 REST API
 *
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for adjustControllerGetChargeJangbuPartnership
     *
     * (해당연월) 장부사의 파트너쉽 금액 조회.
     *
     */
    public function testAdjustControllerGetChargeJangbuPartnership()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adjustControllerGetChargeJangbuPreview
     *
     * .
     *
     */
    public function testAdjustControllerGetChargeJangbuPreview()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adjustControllerRegisterAdjust
     *
     * 정산 등록 (관리자 전용: 극히 일부사용자만).
     *
     */
    public function testAdjustControllerRegisterAdjust()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adjustControllerSearchAdjustJangbuServices
     *
     * 장부사 서비스별 단가 검색 (장부사,관리자 전용).
     *
     */
    public function testAdjustControllerSearchAdjustJangbuServices()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adjustControllerSearchChargeJangbuFromJangbu
     *
     * (특정 장부사의) 정산목록 검색 (장부사 전용).
     *
     */
    public function testAdjustControllerSearchChargeJangbuFromJangbu()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adjustControllerSearchChargeJangbuUserServices
     *
     * 장부사 특정 서비스 회원별 요금목록 검색 (장부사,관리자 전용).
     *
     */
    public function testAdjustControllerSearchChargeJangbuUserServices()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adjustControllerSearchChargeJangbus
     *
     * 정산내역 목록 검색 (관리자 전용).
     *
     */
    public function testAdjustControllerSearchChargeJangbus()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adjustControllerSendChargeJangbuMailTest
     *
     * .
     *
     */
    public function testAdjustControllerSendChargeJangbuMailTest()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adjustControllerUpdateAdjustJangbuService
     *
     * (해당연월) 장부사 특정 서비스 단가를 수정.
     *
     */
    public function testAdjustControllerUpdateAdjustJangbuService()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adjustControllerUpdateChargeJangbuPaid
     *
     * 정산내역 수납여부 업데이트 (관리자 전용: 극히 일부사용자만).
     *
     */
    public function testAdjustControllerUpdateChargeJangbuPaid()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adjustControllerUpdateChargeJangbuPartnership
     *
     * (해당연월) 장부사의 파트너쉽 금액 수정.
     *
     */
    public function testAdjustControllerUpdateChargeJangbuPartnership()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adjustControllerUpdateChargeJangbuStatus
     *
     * 정산내역 비공개 → 공개 상태값 업데이트 및 정산내역 메일 발송 (관리자 전용: 극히 일부사용자만).
     *
     */
    public function testAdjustControllerUpdateChargeJangbuStatus()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for authControllerDeleteToken
     *
     * 로그아웃 (토큰삭제).
     *
     */
    public function testAuthControllerDeleteToken()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for authControllerLogin
     *
     * 토큰발급.
     *
     */
    public function testAuthControllerLogin()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for authControllerRefresh
     *
     * 토큰갱신.
     *
     */
    public function testAuthControllerRefresh()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for errorControllerGetCert
     *
     * 인증서 조회 (관리자 전용: 극히 일부사용자만).
     *
     */
    public function testErrorControllerGetCert()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for errorControllerGetError
     *
     * 에러 조회 (관리자 전용).
     *
     */
    public function testErrorControllerGetError()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for errorControllerGetErrors
     *
     * 에러 목록 검색 (관리자 전용).
     *
     */
    public function testErrorControllerGetErrors()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for jangbuControllerGetJangbu
     *
     * 장부사 조회 (관리자 전용).
     *
     */
    public function testJangbuControllerGetJangbu()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for jangbuControllerGetJangbus
     *
     * 장부사 목록 검색 (관리자 전용).
     *
     */
    public function testJangbuControllerGetJangbus()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for jangbuControllerGetJangbusWithChargeJangbuPartnership
     *
     * (특정연월의 파트너쉽 단가정보와) 장부사 검색 (관리자 전용).
     *
     */
    public function testJangbuControllerGetJangbusWithChargeJangbuPartnership()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for jangbuControllerRegisterJangbu
     *
     * 장부사 등록 (관리자 전용).
     *
     */
    public function testJangbuControllerRegisterJangbu()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for jangbuControllerUpdateJangbu
     *
     * 장부사 수정 (관리자 전용).
     *
     */
    public function testJangbuControllerUpdateJangbu()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for memberControllerFindMember
     *
     * 아이디 찾기 또는 패스워드 찾기.
     *
     */
    public function testMemberControllerFindMember()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for memberControllerGetMember
     *
     * 회원 조회.
     *
     */
    public function testMemberControllerGetMember()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for memberControllerGetMembers
     *
     * 회원 목록 검색.
     *
     */
    public function testMemberControllerGetMembers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for memberControllerGetResetPassword
     *
     * 패스워드 재설정 조회.
     *
     */
    public function testMemberControllerGetResetPassword()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for memberControllerRegisterCustomer
     *
     * (고객사) 계정 등록.
     *
     */
    public function testMemberControllerRegisterCustomer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for memberControllerRegisterMember
     *
     * (관리자 또는 장부사) 계정 등록 (관라지만 이용).
     *
     */
    public function testMemberControllerRegisterMember()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for memberControllerResetPassword
     *
     * (계정찾기진행시) 패스워드 재설정 처리.
     *
     */
    public function testMemberControllerResetPassword()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for memberControllerResetPasswordWithIdEmail
     *
     * 로그인 패스워드 초기화.
     *
     */
    public function testMemberControllerResetPasswordWithIdEmail()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for memberControllerSaveUserRoleGroup
     *
     * 계정의 권한그룹 저장.
     *
     */
    public function testMemberControllerSaveUserRoleGroup()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for memberControllerUpdateMember
     *
     * 계정 수정.
     *
     */
    public function testMemberControllerUpdateMember()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for mobileAppControllerGetAppVersions
     *
     * 앱 버전 목록 검색 (관리자 전용).
     *
     */
    public function testMobileAppControllerGetAppVersions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for mobileAppControllerGetJangbuMessage
     *
     * (특정 장부사의) 메시지 조회 (관리자, 장부사 전용).
     *
     */
    public function testMobileAppControllerGetJangbuMessage()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for mobileAppControllerGetJangbuMessages
     *
     * (특정 장부사의) 메시지 목록 검색 (관리자, 장부사 전용).
     *
     */
    public function testMobileAppControllerGetJangbuMessages()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for mobileAppControllerGetUsingAppUsers
     *
     * 앱 사용자 목록 검색 (관리자 전용).
     *
     */
    public function testMobileAppControllerGetUsingAppUsers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for mobileAppControllerRegisterAppVersion
     *
     * 앱 버전 등록 (관리자 전용).
     *
     */
    public function testMobileAppControllerRegisterAppVersion()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for mobileAppControllerUpdateAppVersion
     *
     * 앱 버전 수정 (관리자 전용).
     *
     */
    public function testMobileAppControllerUpdateAppVersion()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for noticeControllerDeleteNotice
     *
     * 공지사항 삭제 (관리자 전용).
     *
     */
    public function testNoticeControllerDeleteNotice()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for noticeControllerGetNotice
     *
     * 공지사항 조회 (관리자, 장부사 전용).
     *
     */
    public function testNoticeControllerGetNotice()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for noticeControllerGetNotices
     *
     * 공지사항 검색 (관리자, 장부사 전용).
     *
     */
    public function testNoticeControllerGetNotices()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for noticeControllerRegisterNotice
     *
     * 공지사항 등록 (관리자 전용).
     *
     */
    public function testNoticeControllerRegisterNotice()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for noticeControllerUpdateNotice
     *
     * 공지사항 수정 (관리자 전용).
     *
     */
    public function testNoticeControllerUpdateNotice()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for roleControllerGetRoles
     *
     * 권한 목록 검색 (관리자, 장부사 전용).
     *
     */
    public function testRoleControllerGetRoles()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for roleControllerRegisterRole
     *
     * 권한 등록 (관리자 전용).
     *
     */
    public function testRoleControllerRegisterRole()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for roleControllerUpdateRole
     *
     * 권한 수정 (관리자 전용).
     *
     */
    public function testRoleControllerUpdateRole()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for scrapingCodeControllerActivateScrapingCode
     *
     * 코드 활성 여부 변경 (관리자 전용: 극히 일부사용자만).
     *
     */
    public function testScrapingCodeControllerActivateScrapingCode()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for scrapingCodeControllerGetScrapingCodes
     *
     * 스크래핑 코드 목록 검색 (관리자 전용: 극히 일부사용자만).
     *
     */
    public function testScrapingCodeControllerGetScrapingCodes()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for scrapingCodeControllerRegisterScrapingCodeVersion
     *
     * 스크래핑 코드 버전 등록 (Github Action >> Amazon SNS).
     *
     */
    public function testScrapingCodeControllerRegisterScrapingCodeVersion()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for serviceControllerGetService
     *
     * 서비스 조회 (관리자전용).
     *
     */
    public function testServiceControllerGetService()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for serviceControllerGetServices
     *
     * 서비스 목록 검색.
     *
     */
    public function testServiceControllerGetServices()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for serviceControllerRegisterService
     *
     * 서비스 등록 (관리자전용: 일부사용자 or 정산관리자).
     *
     */
    public function testServiceControllerRegisterService()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for serviceControllerUpdateService
     *
     * 서비스 수정 (관리자전용: 일부사용자).
     *
     */
    public function testServiceControllerUpdateService()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workControllerGetWork
     *
     * 업무 조회.
     *
     */
    public function testWorkControllerGetWork()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workControllerGetWorkS3Data
     *
     * (관리자전용) 특정 업무의 S3정보 조회 (업로드 정보 또는 스크래핑 정보).
     *
     */
    public function testWorkControllerGetWorkS3Data()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workControllerGetWorkS3DetailLog
     *
     * 특정 업무의 S3정보의 조회 (업로드 로그).
     *
     */
    public function testWorkControllerGetWorkS3DetailLog()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workControllerGetWorks
     *
     * 업무 목록 검색 (관리자 전용).
     *
     */
    public function testWorkControllerGetWorks()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workControllerGetWorksByJangbu
     *
     * 장부사별 업무 목록 검색 (장부사 전용).
     *
     */
    public function testWorkControllerGetWorksByJangbu()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workControllerGetWorksByUser
     *
     * 사용자별 업무 목록 검색 (고객 전용).
     *
     */
    public function testWorkControllerGetWorksByUser()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workControllerUpdateWork
     *
     * (접수 또는 승인건만) 업무 수정 (관리자 전용: 취소처리).
     *
     */
    public function testWorkControllerUpdateWork()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
