/*
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for FindMemberOutput
 */
public class FindMemberOutputTest {
    private final FindMemberOutput model = new FindMemberOutput();

    /**
     * Model tests for FindMemberOutput
     */
    @Test
    public void testFindMemberOutput() {
        // TODO: test FindMemberOutput
    }

    /**
     * Test the property 'loginId'
     */
    @Test
    public void loginIdTest() {
        // TODO: test loginId
    }

    /**
     * Test the property 'recoveryUrl'
     */
    @Test
    public void recoveryUrlTest() {
        // TODO: test recoveryUrl
    }

}
