/*
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.openapitools.client.model.WorkRequestType;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for WorkDetail
 */
public class WorkDetailTest {
    private final WorkDetail model = new WorkDetail();

    /**
     * Model tests for WorkDetail
     */
    @Test
    public void testWorkDetail() {
        // TODO: test WorkDetail
    }

    /**
     * Test the property 'workId'
     */
    @Test
    public void workIdTest() {
        // TODO: test workId
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'count'
     */
    @Test
    public void countTest() {
        // TODO: test count
    }

    /**
     * Test the property 'transAt'
     */
    @Test
    public void transAtTest() {
        // TODO: test transAt
    }

    /**
     * Test the property 'memo'
     */
    @Test
    public void memoTest() {
        // TODO: test memo
    }

    /**
     * Test the property 'providerType'
     */
    @Test
    public void providerTypeTest() {
        // TODO: test providerType
    }

    /**
     * Test the property 'bizManageNumber'
     */
    @Test
    public void bizManageNumberTest() {
        // TODO: test bizManageNumber
    }

    /**
     * Test the property 'yearMonth'
     */
    @Test
    public void yearMonthTest() {
        // TODO: test yearMonth
    }

    /**
     * Test the property 's3Data'
     */
    @Test
    public void s3DataTest() {
        // TODO: test s3Data
    }

    /**
     * Test the property 'subCode'
     */
    @Test
    public void subCodeTest() {
        // TODO: test subCode
    }

}
