/*
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for WorkResultDetail
 */
public class WorkResultDetailTest {
    private final WorkResultDetail model = new WorkResultDetail();

    /**
     * Model tests for WorkResultDetail
     */
    @Test
    public void testWorkResultDetail() {
        // TODO: test WorkResultDetail
    }

    /**
     * Test the property 'successCount'
     */
    @Test
    public void successCountTest() {
        // TODO: test successCount
    }

    /**
     * Test the property 'failCount'
     */
    @Test
    public void failCountTest() {
        // TODO: test failCount
    }

    /**
     * Test the property 'resultMessage'
     */
    @Test
    public void resultMessageTest() {
        // TODO: test resultMessage
    }

    /**
     * Test the property 'resultPath'
     */
    @Test
    public void resultPathTest() {
        // TODO: test resultPath
    }

}
