/* tslint:disable */
/* eslint-disable */
/**
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetCertOutput
 */
export interface GetCertOutput {
    /**
     * 인증서 HEX
     * @type {string}
     * @memberof GetCertOutput
     */
    cert: string;
    /**
     * 비밀번호
     * @type {string}
     * @memberof GetCertOutput
     */
    passphrase: string;
    /**
     * 개인키 HEX
     * @type {string}
     * @memberof GetCertOutput
     */
    privateKey: string;
    /**
     * 확장정보
     * @type {object}
     * @memberof GetCertOutput
     */
    extra?: object | null;
}

export function GetCertOutputFromJSON(json: any): GetCertOutput {
    return GetCertOutputFromJSONTyped(json, false);
}

export function GetCertOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCertOutput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cert': json['cert'],
        'passphrase': json['passphrase'],
        'privateKey': json['privateKey'],
        'extra': !exists(json, 'extra') ? undefined : json['extra'],
    };
}

export function GetCertOutputToJSON(value?: GetCertOutput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cert': value.cert,
        'passphrase': value.passphrase,
        'privateKey': value.privateKey,
        'extra': value.extra,
    };
}


