/* tslint:disable */
/* eslint-disable */
/**
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Jangbu,
    JangbuFromJSON,
    JangbuFromJSONTyped,
    JangbuToJSON,
    PagingLinks,
    PagingLinksFromJSON,
    PagingLinksFromJSONTyped,
    PagingLinksToJSON,
    PagingMeta,
    PagingMetaFromJSON,
    PagingMetaFromJSONTyped,
    PagingMetaToJSON,
} from './';

/**
 * 
 * @export
 * @interface GetJangbusOutput
 */
export interface GetJangbusOutput {
    /**
     * 장부사 목록
     * @type {Array<Jangbu>}
     * @memberof GetJangbusOutput
     */
    readonly items: Array<Jangbu>;
    /**
     * 페이징 메타정보
     * @type {PagingMeta}
     * @memberof GetJangbusOutput
     */
    readonly meta: PagingMeta;
    /**
     * 페이징 링크정보
     * @type {PagingLinks}
     * @memberof GetJangbusOutput
     */
    readonly links: PagingLinks;
}

export function GetJangbusOutputFromJSON(json: any): GetJangbusOutput {
    return GetJangbusOutputFromJSONTyped(json, false);
}

export function GetJangbusOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetJangbusOutput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(JangbuFromJSON)),
        'meta': PagingMetaFromJSON(json['meta']),
        'links': PagingLinksFromJSON(json['links']),
    };
}

export function GetJangbusOutputToJSON(value?: GetJangbusOutput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}


