/* tslint:disable */
/* eslint-disable */
/**
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum OsType {
    I = 'I',
    A = 'A'
}

export function OsTypeFromJSON(json: any): OsType {
    return OsTypeFromJSONTyped(json, false);
}

export function OsTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): OsType {
    return json as OsType;
}

export function OsTypeToJSON(value?: OsType | null): any {
    return value as any;
}

