/* tslint:disable */
/* eslint-disable */
/**
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RefreshOutput
 */
export interface RefreshOutput {
    /**
     * 엑세스토큰
     * @type {string}
     * @memberof RefreshOutput
     */
    accessToken: string;
    /**
     * 리프레시토큰
     * @type {string}
     * @memberof RefreshOutput
     */
    refreshToken: string;
}

export function RefreshOutputFromJSON(json: any): RefreshOutput {
    return RefreshOutputFromJSONTyped(json, false);
}

export function RefreshOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefreshOutput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessToken': json['accessToken'],
        'refreshToken': json['refreshToken'],
    };
}

export function RefreshOutputToJSON(value?: RefreshOutput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accessToken': value.accessToken,
        'refreshToken': value.refreshToken,
    };
}


