/* tslint:disable */
/* eslint-disable */
/**
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AdjustJangbuService,
    AdjustJangbuServiceFromJSON,
    AdjustJangbuServiceFromJSONTyped,
    AdjustJangbuServiceToJSON,
    ChargeJangbu,
    ChargeJangbuFromJSON,
    ChargeJangbuFromJSONTyped,
    ChargeJangbuToJSON,
    ChargeJangbuPartnership,
    ChargeJangbuPartnershipFromJSON,
    ChargeJangbuPartnershipFromJSONTyped,
    ChargeJangbuPartnershipToJSON,
} from './';

/**
 * 
 * @export
 * @interface RegisterAdjustOutput
 */
export interface RegisterAdjustOutput {
    /**
     * 진행된 정산내역 등록단계
     * @type {number}
     * @memberof RegisterAdjustOutput
     */
    step: number;
    /**
     * (1단계진행시 반환정보) 장부사 서비스별 단가목록
     * @type {Array<AdjustJangbuService>}
     * @memberof RegisterAdjustOutput
     */
    adjustJangbuServices?: Array<AdjustJangbuService> | null;
    /**
     * (1단계진행시 반환정보) 장부사 계좌통합서비스 정보
     * @type {ChargeJangbuPartnership}
     * @memberof RegisterAdjustOutput
     */
    chargeJangbuPartnership?: ChargeJangbuPartnership | null;
    /**
     * (2단계진행시 반환정보) 해당연월 장부사 정산금액
     * @type {ChargeJangbu}
     * @memberof RegisterAdjustOutput
     */
    chargeJangbu?: ChargeJangbu | null;
}

export function RegisterAdjustOutputFromJSON(json: any): RegisterAdjustOutput {
    return RegisterAdjustOutputFromJSONTyped(json, false);
}

export function RegisterAdjustOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterAdjustOutput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'step': json['step'],
        'adjustJangbuServices': !exists(json, 'adjustJangbuServices') ? undefined : (json['adjustJangbuServices'] === null ? null : (json['adjustJangbuServices'] as Array<any>).map(AdjustJangbuServiceFromJSON)),
        'chargeJangbuPartnership': !exists(json, 'chargeJangbuPartnership') ? undefined : ChargeJangbuPartnershipFromJSON(json['chargeJangbuPartnership']),
        'chargeJangbu': !exists(json, 'chargeJangbu') ? undefined : ChargeJangbuFromJSON(json['chargeJangbu']),
    };
}

export function RegisterAdjustOutputToJSON(value?: RegisterAdjustOutput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'step': value.step,
        'adjustJangbuServices': value.adjustJangbuServices === undefined ? undefined : (value.adjustJangbuServices === null ? null : (value.adjustJangbuServices as Array<any>).map(AdjustJangbuServiceToJSON)),
        'chargeJangbuPartnership': ChargeJangbuPartnershipToJSON(value.chargeJangbuPartnership),
        'chargeJangbu': ChargeJangbuToJSON(value.chargeJangbu),
    };
}


