/* tslint:disable */
/* eslint-disable */
/**
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RegisterJangbuInputDetailJangbu,
    RegisterJangbuInputDetailJangbuFromJSON,
    RegisterJangbuInputDetailJangbuFromJSONTyped,
    RegisterJangbuInputDetailJangbuToJSON,
    RegisterJangbuInputDetailUser,
    RegisterJangbuInputDetailUserFromJSON,
    RegisterJangbuInputDetailUserFromJSONTyped,
    RegisterJangbuInputDetailUserToJSON,
} from './';

/**
 * 
 * @export
 * @interface RegisterJangbuInput
 */
export interface RegisterJangbuInput {
    /**
     * 등록할 장부사 정보
     * @type {RegisterJangbuInputDetailJangbu}
     * @memberof RegisterJangbuInput
     */
    jangbu: RegisterJangbuInputDetailJangbu;
    /**
     * 등록할 장부사 회원 정보
     * @type {RegisterJangbuInputDetailUser}
     * @memberof RegisterJangbuInput
     */
    user: RegisterJangbuInputDetailUser;
    /**
     * 이용할 서비스 목록
     * @type {Array<number>}
     * @memberof RegisterJangbuInput
     */
    serviceIds: Array<RegisterJangbuInputServiceIdsEnum>;
}

/**
* @export
* @enum {string}
*/
export enum RegisterJangbuInputServiceIdsEnum {
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6,
    NUMBER_7 = 7,
    NUMBER_8 = 8,
    NUMBER_9 = 9,
    NUMBER_10 = 10
}

export function RegisterJangbuInputFromJSON(json: any): RegisterJangbuInput {
    return RegisterJangbuInputFromJSONTyped(json, false);
}

export function RegisterJangbuInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterJangbuInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jangbu': RegisterJangbuInputDetailJangbuFromJSON(json['jangbu']),
        'user': RegisterJangbuInputDetailUserFromJSON(json['user']),
        'serviceIds': json['serviceIds'],
    };
}

export function RegisterJangbuInputToJSON(value?: RegisterJangbuInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jangbu': RegisterJangbuInputDetailJangbuToJSON(value.jangbu),
        'user': RegisterJangbuInputDetailUserToJSON(value.user),
        'serviceIds': value.serviceIds,
    };
}


