/* tslint:disable */
/* eslint-disable */
/**
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Recovery,
    RecoveryFromJSON,
    RecoveryFromJSONTyped,
    RecoveryToJSON,
} from './';

/**
 * 
 * @export
 * @interface ResetPasswordOutput
 */
export interface ResetPasswordOutput {
    /**
     * 비밀번호 초기화 정보
     * @type {Recovery}
     * @memberof ResetPasswordOutput
     */
    recovery: Recovery;
}

export function ResetPasswordOutputFromJSON(json: any): ResetPasswordOutput {
    return ResetPasswordOutputFromJSONTyped(json, false);
}

export function ResetPasswordOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResetPasswordOutput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'recovery': RecoveryFromJSON(json['recovery']),
    };
}

export function ResetPasswordOutputToJSON(value?: ResetPasswordOutput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'recovery': RecoveryToJSON(value.recovery),
    };
}


