/* tslint:disable */
/* eslint-disable */
/**
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RoleName,
    RoleNameFromJSON,
    RoleNameFromJSONTyped,
    RoleNameToJSON,
} from './';

/**
 * 
 * @export
 * @interface RoleGroupMapping
 */
export interface RoleGroupMapping {
    /**
     * 
     * @type {RoleName}
     * @memberof RoleGroupMapping
     */
    roleName: RoleName;
    /**
     * 접근 권한(읽기 : r, 쓰기 : w)
     * @type {string}
     * @memberof RoleGroupMapping
     */
    permission: RoleGroupMappingPermissionEnum;
}

/**
* @export
* @enum {string}
*/
export enum RoleGroupMappingPermissionEnum {
    R = 'r',
    W = 'w'
}

export function RoleGroupMappingFromJSON(json: any): RoleGroupMapping {
    return RoleGroupMappingFromJSONTyped(json, false);
}

export function RoleGroupMappingFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleGroupMapping {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'roleName': RoleNameFromJSON(json['roleName']),
        'permission': json['permission'],
    };
}

export function RoleGroupMappingToJSON(value?: RoleGroupMapping | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'roleName': RoleNameToJSON(value.roleName),
        'permission': value.permission,
    };
}


