/* tslint:disable */
/* eslint-disable */
/**
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendChagreJangbuMailTestInput
 */
export interface SendChagreJangbuMailTestInput {
    /**
     * 수신자 이메일
     * @type {string}
     * @memberof SendChagreJangbuMailTestInput
     */
    email: string;
}

export function SendChagreJangbuMailTestInputFromJSON(json: any): SendChagreJangbuMailTestInput {
    return SendChagreJangbuMailTestInputFromJSONTyped(json, false);
}

export function SendChagreJangbuMailTestInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendChagreJangbuMailTestInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function SendChagreJangbuMailTestInputToJSON(value?: SendChagreJangbuMailTestInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
    };
}


