/* tslint:disable */
/* eslint-disable */
/**
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Jangbu,
    JangbuFromJSON,
    JangbuFromJSONTyped,
    JangbuToJSON,
} from './';

/**
 * 
 * @export
 * @interface SendChargeJangbuMailTestOutput
 */
export interface SendChargeJangbuMailTestOutput {
    /**
     * 수신자 이메일
     * @type {string}
     * @memberof SendChargeJangbuMailTestOutput
     */
    email: string;
    /**
     * 장부사
     * @type {Jangbu}
     * @memberof SendChargeJangbuMailTestOutput
     */
    jangbu: Jangbu;
}

export function SendChargeJangbuMailTestOutputFromJSON(json: any): SendChargeJangbuMailTestOutput {
    return SendChargeJangbuMailTestOutputFromJSONTyped(json, false);
}

export function SendChargeJangbuMailTestOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendChargeJangbuMailTestOutput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'jangbu': JangbuFromJSON(json['jangbu']),
    };
}

export function SendChargeJangbuMailTestOutputToJSON(value?: SendChargeJangbuMailTestOutput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'jangbu': JangbuToJSON(value.jangbu),
    };
}


