/* tslint:disable */
/* eslint-disable */
/**
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ServiceCategory {
     = '회계업로드',
     = '계좌통합',
     = '음식배달',
    Edi = 'EDI'
}

export function ServiceCategoryFromJSON(json: any): ServiceCategory {
    return ServiceCategoryFromJSONTyped(json, false);
}

export function ServiceCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceCategory {
    return json as ServiceCategory;
}

export function ServiceCategoryToJSON(value?: ServiceCategory | null): any {
    return value as any;
}

