/* tslint:disable */
/* eslint-disable */
/**
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SlipSplitDeleteUploadSlip
 */
export interface SlipSplitDeleteUploadSlip {
    /**
     * 일자(YYYYMMDD)
     * @type {string}
     * @memberof SlipSplitDeleteUploadSlip
     */
    bILLDATE: string;
    /**
     * 
     * @type {string}
     * @memberof SlipSplitDeleteUploadSlip
     */
    bILLORDERDATE: string;
    /**
     * 과목코드
     * @type {string}
     * @memberof SlipSplitDeleteUploadSlip
     */
    eSTICODE: string;
    /**
     * 입출구분(I:세입, O:세출)
     * @type {string}
     * @memberof SlipSplitDeleteUploadSlip
     */
    eSTIINOUT: string;
    /**
     * 
     * @type {string}
     * @memberof SlipSplitDeleteUploadSlip
     */
    bILLMONEY: string;
    /**
     * 전표메모(공란)
     * @type {string}
     * @memberof SlipSplitDeleteUploadSlip
     */
    bILLMEMO: string;
    /**
     * 비고내용
     * @type {string}
     * @memberof SlipSplitDeleteUploadSlip
     */
    bILLBIGO: string;
    /**
     * 
     * @type {string}
     * @memberof SlipSplitDeleteUploadSlip
     */
    bILLSUPPORTAT: string;
    /**
     * 
     * @type {string}
     * @memberof SlipSplitDeleteUploadSlip
     */
    bILLNURIAT: string;
    /**
     * 
     * @type {string}
     * @memberof SlipSplitDeleteUploadSlip
     */
    sETLEMTHD: string;
    /**
     * 
     * @type {string}
     * @memberof SlipSplitDeleteUploadSlip
     */
    eSTIIDX: string;
    /**
     * 
     * @type {string}
     * @memberof SlipSplitDeleteUploadSlip
     */
    eSTINAME: string;
    /**
     * 
     * @type {string}
     * @memberof SlipSplitDeleteUploadSlip
     */
    eSTIDEPTH: string;
    /**
     * 
     * @type {string}
     * @memberof SlipSplitDeleteUploadSlip
     */
    eSTINAME1: string;
    /**
     * 
     * @type {string}
     * @memberof SlipSplitDeleteUploadSlip
     */
    eSTINAME2: string;
    /**
     * 
     * @type {string}
     * @memberof SlipSplitDeleteUploadSlip
     */
    eSTINAME3: string;
}

export function SlipSplitDeleteUploadSlipFromJSON(json: any): SlipSplitDeleteUploadSlip {
    return SlipSplitDeleteUploadSlipFromJSONTyped(json, false);
}

export function SlipSplitDeleteUploadSlipFromJSONTyped(json: any, ignoreDiscriminator: boolean): SlipSplitDeleteUploadSlip {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bILLDATE': json['BILL_DATE'],
        'bILLORDERDATE': json['BILL_ORDER_DATE'],
        'eSTICODE': json['ESTI_CODE'],
        'eSTIINOUT': json['ESTI_INOUT'],
        'bILLMONEY': json['BILL_MONEY'],
        'bILLMEMO': json['BILL_MEMO'],
        'bILLBIGO': json['BILL_BIGO'],
        'bILLSUPPORTAT': json['BILL_SUPPORT_AT'],
        'bILLNURIAT': json['BILL_NURI_AT'],
        'sETLEMTHD': json['SETLE_MTHD'],
        'eSTIIDX': json['ESTI_IDX'],
        'eSTINAME': json['ESTI_NAME'],
        'eSTIDEPTH': json['ESTI_DEPTH'],
        'eSTINAME1': json['ESTI_NAME_1'],
        'eSTINAME2': json['ESTI_NAME_2'],
        'eSTINAME3': json['ESTI_NAME_3'],
    };
}

export function SlipSplitDeleteUploadSlipToJSON(value?: SlipSplitDeleteUploadSlip | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'BILL_DATE': value.bILLDATE,
        'BILL_ORDER_DATE': value.bILLORDERDATE,
        'ESTI_CODE': value.eSTICODE,
        'ESTI_INOUT': value.eSTIINOUT,
        'BILL_MONEY': value.bILLMONEY,
        'BILL_MEMO': value.bILLMEMO,
        'BILL_BIGO': value.bILLBIGO,
        'BILL_SUPPORT_AT': value.bILLSUPPORTAT,
        'BILL_NURI_AT': value.bILLNURIAT,
        'SETLE_MTHD': value.sETLEMTHD,
        'ESTI_IDX': value.eSTIIDX,
        'ESTI_NAME': value.eSTINAME,
        'ESTI_DEPTH': value.eSTIDEPTH,
        'ESTI_NAME_1': value.eSTINAME1,
        'ESTI_NAME_2': value.eSTINAME2,
        'ESTI_NAME_3': value.eSTINAME3,
    };
}


