/* tslint:disable */
/* eslint-disable */
/**
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SlipSplitDeleteUploadBank
 */
export interface SlipSplitDeleteUploadBank {
    /**
     * 거래일시(YYYYMMDD)
     * @type {object}
     * @memberof SlipSplitDeleteUploadBank
     */
    tRANSDATETIME?: object | null;
    /**
     * 일자(YYYYMMDD)
     * @type {object}
     * @memberof SlipSplitDeleteUploadBank
     */
    tRANSDATE?: object | null;
    /**
     * 거래내역 입출구분 (I/O)
     * @type {object}
     * @memberof SlipSplitDeleteUploadBank
     */
    tRANSGB?: object | null;
    /**
     * 거래금액
     * @type {object}
     * @memberof SlipSplitDeleteUploadBank
     */
    tRANSMONEY?: object | null;
    /**
     * 입금액(출금거래시 0)
     * @type {object}
     * @memberof SlipSplitDeleteUploadBank
     */
    tRANSMONEYIN?: object | null;
    /**
     * 출금액(입금거래시 0)
     * @type {object}
     * @memberof SlipSplitDeleteUploadBank
     */
    tRANSMONEYOUT?: object | null;
    /**
     * 거래후 잔액
     * @type {object}
     * @memberof SlipSplitDeleteUploadBank
     */
    tRANSREMAIN?: object | null;
    /**
     * 거래내용(적요)
     * @type {object}
     * @memberof SlipSplitDeleteUploadBank
     */
    tRANSMEMO?: object | null;
}

export function SlipSplitDeleteUploadBankFromJSON(json: any): SlipSplitDeleteUploadBank {
    return SlipSplitDeleteUploadBankFromJSONTyped(json, false);
}

export function SlipSplitDeleteUploadBankFromJSONTyped(json: any, ignoreDiscriminator: boolean): SlipSplitDeleteUploadBank {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tRANSDATETIME': !exists(json, 'TRANS_DATETIME') ? undefined : json['TRANS_DATETIME'],
        'tRANSDATE': !exists(json, 'TRANS_DATE') ? undefined : json['TRANS_DATE'],
        'tRANSGB': !exists(json, 'TRANS_GB') ? undefined : json['TRANS_GB'],
        'tRANSMONEY': !exists(json, 'TRANS_MONEY') ? undefined : json['TRANS_MONEY'],
        'tRANSMONEYIN': !exists(json, 'TRANS_MONEY_IN') ? undefined : json['TRANS_MONEY_IN'],
        'tRANSMONEYOUT': !exists(json, 'TRANS_MONEY_OUT') ? undefined : json['TRANS_MONEY_OUT'],
        'tRANSREMAIN': !exists(json, 'TRANS_REMAIN') ? undefined : json['TRANS_REMAIN'],
        'tRANSMEMO': !exists(json, 'TRANS_MEMO') ? undefined : json['TRANS_MEMO'],
    };
}

export function SlipSplitDeleteUploadBankToJSON(value?: SlipSplitDeleteUploadBank | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'TRANS_DATETIME': value.tRANSDATETIME,
        'TRANS_DATE': value.tRANSDATE,
        'TRANS_GB': value.tRANSGB,
        'TRANS_MONEY': value.tRANSMONEY,
        'TRANS_MONEY_IN': value.tRANSMONEYIN,
        'TRANS_MONEY_OUT': value.tRANSMONEYOUT,
        'TRANS_REMAIN': value.tRANSREMAIN,
        'TRANS_MEMO': value.tRANSMEMO,
    };
}


