/* tslint:disable */
/* eslint-disable */
/**
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RoleGroupMapping,
    RoleGroupMappingFromJSON,
    RoleGroupMappingFromJSONTyped,
    RoleGroupMappingToJSON,
} from './';

/**
 * 
 * @export
 * @interface UpdateRoleGroupInput
 */
export interface UpdateRoleGroupInput {
    /**
     * 권한그룹명
     * @type {string}
     * @memberof UpdateRoleGroupInput
     */
    name: string;
    /**
     * 권한그룹 설명
     * @type {string}
     * @memberof UpdateRoleGroupInput
     */
    desc?: string | null;
    /**
     * 권한 이름과 접근 권한 목록
     * @type {Array<RoleGroupMapping>}
     * @memberof UpdateRoleGroupInput
     */
    roles: Array<RoleGroupMapping>;
    /**
     * 활성 여부
     * @type {boolean}
     * @memberof UpdateRoleGroupInput
     */
    active: boolean;
}

export function UpdateRoleGroupInputFromJSON(json: any): UpdateRoleGroupInput {
    return UpdateRoleGroupInputFromJSONTyped(json, false);
}

export function UpdateRoleGroupInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateRoleGroupInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'desc': !exists(json, 'desc') ? undefined : json['desc'],
        'roles': ((json['roles'] as Array<any>).map(RoleGroupMappingFromJSON)),
        'active': json['active'],
    };
}

export function UpdateRoleGroupInputToJSON(value?: UpdateRoleGroupInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'desc': value.desc,
        'roles': ((value.roles as Array<any>).map(RoleGroupMappingToJSON)),
        'active': value.active,
    };
}


