/* tslint:disable */
/* eslint-disable */
/**
 * 뱅크다K 웹앱 REST API
 * 뱅크다K 웹앱 REST API : 관리자, 장부사, 고객사
 *
 * The version of the OpenAPI document: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum UserServiceType {
     = '경기형',
    W4c = 'w4c',
     = '음식배달',
    Edi = 'EDI',
     = '서울형',
     = '증빙앱',
     = '대구형',
     = '인천형'
}

export function UserServiceTypeFromJSON(json: any): UserServiceType {
    return UserServiceTypeFromJSONTyped(json, false);
}

export function UserServiceTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserServiceType {
    return json as UserServiceType;
}

export function UserServiceTypeToJSON(value?: UserServiceType | null): any {
    return value as any;
}

